### ISSUE TITLE
I need ios 12.1.4 jaipbreak

### ISSUE THREAD

**Issue by kelvin660909** [pwn20wndstuff/Undecimus#1109]
**Describe the feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Cvenos** [comment]
we understand that you need an iOS 12.1.4 but unfortunately pwn20wnd doesn’t just make jailbreaks out of thin air and people like you need to stop making these “feature requests” for a jailbreak for a higher version. he does the best he can and he could just implement some sort of malware into this jailbreak at any point of time but he’s not an annoying faggot sitting here begging for something which is impossible and will never get. so yourself is the one to blame that you are not jailbroken because since like November of 2018 people were saying “Stay on the lowest possible firmware because a jailbreak could come out soon” and you chose not to listen therefore it is your fault and stop bugging pwn20wnd about making a jailbreak for a higher version because it’s annoying and not funny at all.

**Comment by Pythonic-Rainbow** [comment]
He simply doesn't know what GitHub is. He doesn't even use the template at all. I suggest closing this issue as the devs obviously know we want.

**Comment by Assfugil** [comment]
Ok now you have it please close this.
