### ISSUE TITLE
[Question] : Supported devices for voucher_swap

### ISSUE THREAD

**Issue by MrKris99** [pwn20wndstuff/Undecimus#1110]
Can you tell me about supported iOS-es \ devices for your implementation of voucher_swap exploit?

**Comment by TheRealKeto** [comment]
Voucher_swap supports all A9-A12X devices. Unsupported devices would be A7 and A8 devices, which is why the initial release of unc0ver for iOS 12 only supported the iPhone 6 and above (except for A12 devices), and why A7-A8 devices instead use mach_swap1. 

Theoretically speaking, voucher_swap supports all iOS versions (except this is incorrect to some extend) but it was release for devices running iOS 12-12.1.2.  It does not support later versions.

**Comment by MrKris99** [comment]
@TheRealKeto  Thanks. But what about supported version in this repo?
Is it supports voucher_swap for some part of iOS 11 ?

**Comment by yousef157** [comment]
doesnt support my iPad Air (iPad 4,1) 12.1.1 stable

machswap works 4 me

**Comment by TheRealKeto** [comment]
> @TheRealKeto Thanks. But what about supported versions in this repo?
> Is it supports voucher_swap for some part of iOS 11?

@MrKris99 Like I mentioned before, voucher_swap (theoretically) supports all iOS firmwares, even iOS 11, however, this is why unc0ver has different exploits within the app, in case one doesn't work for your device. If that's the case, then simply select another exploit (such as mach_swap2) and try again.
