### ISSUE TITLE
Errno 60

### ISSUE THREAD

**Issue by xXPocketknifeXx** [pwn20wndstuff/Undecimus#118]
![830f7446-074d-44e6-929d-58bc7e2e5ea1](https://user-images.githubusercontent.com/44234112/48656089-0d956300-e9d5-11e8-8c18-a4b5d2adae6a.png)

Usually UnC0ver works when I reinstall it but this time it didn’t. UnC0ver version: V1.1.4

**Comment by Kimo76** [comment]
Same exact issue I have. Always been able to re-jailbreak IPhone 7 Plus on 11.3.1 until this latest version 1.1.4

**Comment by xXPocketknifeXx** [comment]
Does the issue have to do with Tweakbox? I downloaded UnC0ver from Tweakbox. I deleted everything that had to do with Tweakbox. Still failed. Tried loading in UnC0ver with Impactor still the same issue. Idk what to do now.😢

**Comment by Kimo76** [comment]
That is what I was going to do too since I have been using tweakbox for unc0ver since the beginning and all was fine until version 1.1.4. I don’t think we are the only ones. I tried other version like 1.1.1 and RC6 from AppValley and still nothing different error same result. I don’t think it had to do with the future restore I did a while back since all other version worked for before this one. The only reason I have to rejailbreak is cause my phone froze when I tried to mirror my phone to my tv and I was force to shutdown with the volume down and power button.

**Comment by Kimo76** [comment]
Let me know if you find a solution and I’ll do the same.

**Comment by Kimo76** [comment]
I disabled Siri, and turn passcode off. After about 8 tries it worked. I used the tweakbox version 1.1.4 of unc0ver. Finally!!!!!

**Comment by Samgisaninja** [comment]
The exploit doesn’t work 100% of the time. There is nothing we can do about this.

**Comment by StormJ** [comment]
I have same issue on iP5s iOS 11.3.1 and I used Electra first with Impactor, than MP version over Ignition.fun and than it crashed all the time. I switched to unc0ver and still same issue. EL or MP make no difference(EL respring iPhone on 1/51 and MP giving me error 60)
![ip5s 11 3 1](https://user-images.githubusercontent.com/45273199/48921686-d1b14080-eea1-11e8-8a72-68e408b43d47.PNG)

**Comment by Samgisaninja** [comment]
The signing services recently broke their multipath entitlements, there is nothing we can do about this either.

empty_list will work eventually, it's just less reliable and you just have to be patient with it. I'd recommend signing unc0ver with Impactor instead of using a signing service.

Locking this discussion as the signing services messing up their certs is not an issue on our end, and there's nothing we can do about this.
