### ISSUE TITLE
Help,can not connect 127.0.0.1 22 through ssh

### ISSUE THREAD

**Issue by flhang** [pwn20wndstuff/Undecimus#1208]
Hi, my model is iphone xs max. I jailbroken successfully via unc0ver! . And I can ssh to iphone via putty on my PC(ip is 192.168.0.x). 
However, I can not use any app ssh to 127.0.0.1 : 22, or my wifi ip 192.168.0.x . I tried serveral apps, For example, termius fails.
Please help!

**Comment by hamid0015** [comment]
install Local SSH from chariz repo then ssh again. try 2222 port for localhost

**Comment by flhang** [comment]
thank you for reply. I am wondering if there is a "apt-get" like package manager in iphone darwin os?

**Comment by riotdream** [comment]
you can also change SSH port in /etc/ssh/sshd_config

where you can read "Port 22" to "Port 4321" or whatever you like.

**Comment by badger200** [comment]
**EDIT:** All these are false! The **solution is simple! Just edit the com.openssh.sshd.plist in LaunchDaemon**s (I think /System/Library) and **change the Socket/port from “ssh” to say “2222”** instead! That’s it! 😃

> you can also change SSH port in /etc/ssh/sshd_config
> 
> where you can read "Port 22" to "Port 4321" or whatever you like.

I have been trying this but unc0ver doesn’t seem to even use sshd_config. If you look at the LaunchDaemon .plist it doesn’t use the -f config_file option.

I’m desperate to switch it to port 2222 because port 22 is useless, as @flhang experienced **because iOS deliberately blocks any app from connecting to localhost:22.**

**Comment by Potterd** [comment]
Am also interested in how to SSH to Localhost while using Unc0ver .....
