### ISSUE TITLE
Can't update apps from AppStore.

### ISSUE THREAD

**Issue by ASILVAPT** [pwn20wndstuff/Undecimus#1220]
**Describe the bug**
Hi,

Since I update the unc0ver for the last version in my iPhone I can’t update apps on AppStore just getting error is unable to download the app.

I already tried uninstall all my tweaks, re-jailbreak, restarts and still the same issue.

Regards.

**To Reproduce**
1. Go to 'AppStore'
2. Click on 'Update Apps'
3. See error.

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone 8
 - unc0ver Version: Lastest

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by Martin-SF** [comment]
Have you tried restore rootFS? It’s more clean than manually uninstalling all your tweaks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kai0KenX20** [comment]
Not sure if this will help but i had your exact same issue on 12.1.2 turned out one of the system daemons was disabled try installing iCleaner and check to make sure ALL of them are enabled even the OTA update one if your worried about the possibility of an OTA update happening during the check first check to make sure you dont already have it downloaded in your iPhone storage (Settings/General/iPhone Storage) and install the tvOS beta profile to block them if you havent already....... Link to tvOS Beta Profile if needed https://betaprofiles.com/tvos ... Open with Safari
