### ISSUE TITLE
[Question] Is any updates are closed source now?

### ISSUE THREAD

**Issue by krisanovdev** [pwn20wndstuff/Undecimus#1228]
I do not see updates for 12.1.3 - 12.2 (sock port exploit). Is it closed source?

**Comment by bigrck64** [comment]
Confirmed here :(
When I git clone --recursive https://github.com/pwn20wndstuff/Undecimus.git
I got the 3.3.0 project.

I also tried to replace git sources files with the "v3.4.2 source code" from Release page
https://github.com/pwn20wndstuff/Undecimus/archive/v3.4.2.zip
And got the same result: 3.3.0 project with Voucher Swap exploit.

Please update repo ! :+1:

**Comment by clubby789** [comment]
https://www.reddit.com/r/jailbreak/comments/c7ggma/discussion_my_thoughts_about_open_source/
Based on this, it sounds like he's planning to release source updates with a lag behind the releases. This is to ensure that the original will be ahead of any clones, so people can't make their own with mal/adware. He didn't explicitly say he would do it, but it looks like he has

**Comment by bigrck64** [comment]
Thanks for the link, good reading :)
pwn20wnd should just ignore clones, nobody use them and we all know unc0ver is the only main universal jailbreak since October 2018.
About abuse in the repo (Issues, Pull request, etc.), I would suggest to name a few moderators for keeping the repo clean, so it won't disturb pwn & sam.

Let's hope we will see the delayed source update as promised, I don't want another chimera :)
