### ISSUE TITLE
iPhone 7 bootloop

### ISSUE THREAD

**Issue by darkwar123** [pwn20wndstuff/Undecimus#1281]
After successful rootfs screenshot device was restarting and showed infinite apple logo. But if i connect it by USB iTunes sees the device. 

 iPhone 7 64GB IOS 12.4

**Comment by some100** [comment]
Force Restart the device by pressing both and holding both the Volume Down button and the sleep button. When the apple logo appears and you still have Cydia installed, you might have to press and hold volume up and down. But you might not need to do that. That's how you solve the problem for an iPhone 7.
Otherwise, if above doesn't work, you might have to Recovery Mode, which if you don't have a backup specifically for your iPhone in your computer you have no choice but to DFU reset and start all over with DFU mode method. Unless, of course, you have an iCloud to restore from.
