### ISSUE TITLE
The Cydia icon does not exist after jailbreak, but you can open cydia via U0.

### ISSUE THREAD

**Issue by mskgroup** [pwn20wndstuff/Undecimus#1284]
**Describe the bug**
The Cydia icon does not exist after jailbreak, but you can open cydia via U0.

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: ipad air 2
 - unc0ver Version: 3.5.2

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by yiggypiggy** [comment]
I'm having the same problem.

- iOS Version: 12.4
- iOS Device: ipad air 2
- unc0ver Version: 3.5.2

**Comment by jkister** [comment]
did you both try "refresh icon cache" in unc0ver settings?

**Comment by yiggypiggy** [comment]
Yes, still the same.

**Comment by c-hri-s** [comment]
Same for me - also on an iPad Air 2, 12.4. 
Completely fresh install - not an upgrade - no restore performed.

Also icons for things installed via Cydia (opened from U0) don't show up either.
Tried both rebooting and 'refresh icon cache'

**Comment by maheralqudah** [comment]
![1864CD78-DA12-4251-BC01-A42C8A570438](https://user-images.githubusercontent.com/54306657/63326882-cce8c280-c335-11e9-85b4-d29e94522a8d.png)

My friend gave me some links for sources that I can use, when O added them to my sources the upgrade icon appears so I clicked on it and the cydia instantly closed and I couldn’t open it again, every time I tried to open it it shuts down before the screen appears so I tried to delete cydia and redo jailbreak but unfortunately the app doesn’t exist but I think that the app in just hidden then because when I tried to install app there was an space between apps, anyway I tried to fix this but I accidentally destroy everything because I tried to uninstall all apps I used to jailbreak the iPhone and delete all profiles from general setting and reinstall it but the jailbreak didn’t work, so last thing I did is reset all setting and reinstall all jailbreak apps and jailbreak the iPhone but still didn’t work and always the iPhone restart after reaching 8/31 

Is there any solution for this or I have to do software for my iPhone !

**Comment by c-hri-s** [comment]
I redid the jailbreak and selected to add OpenSSH.
Not sure if this is what changed anything, but the icons then appeared after a reboot/rejailbreak

**Comment by maheralqudah** [comment]
It didn’t work with me 
> I redid the jailbreak and selected to add OpenSSH.
> Not sure if this is what changed anything, but the icons then appeared after a reboot/rejailbreak

**Comment by erickyim** [comment]
I'm having the same problem.

- iOS Version: 12.4
- iOS Device: ipad air 2
- unc0ver Version: 3.5.6

I reinstalled **unc0ver v3.5.5**  and it works.
