### ISSUE TITLE
Latest app updates won’t launch on iPad Air (a7)

### ISSUE THREAD

**Issue by lewis0917** [pwn20wndstuff/Undecimus#1317]
So I’ve fallen back to 3.3.6. I’m guessing this affects the latest firmware jailbreak?

**Comment by lewis0917** [comment]
Must I be running ios 12 for the latest UØ to work?

**Comment by hongsolo9** [comment]
Are you running on iOS 12.4 currently?

**Comment by lewis0917** [comment]
Running iOS 11. Must I update to latest firmware to attempt this newest jailbreak?

**Comment by lewis0917** [comment]
I mean as it stands the latest versions of uO crash on launch.

**Comment by hongsolo9** [comment]
I got the iPad Air updated to iOS12.4 and had luck with unc0ver 3.5.0 instead of 3.5.1 and 3.5.2. unc0ver 3.5.0 took multiple tries before it jb'ed the iPad Air. Each try took about a minute or so. Here's couple tips that helped me.

1. Load unc0ver 3.5.0 via Impactor
2. Remember to enable certificate installation (Device Management) via Settings -> General -> Device Management
3. Reboot the iPad and get into flight mode.
4. Long press on the home button to get rid of existing apps in the memory
5. Run unc0ver but don't click on the Jailbreak button yet.
6. Let the iPad rest for about a minute before running the Jailbreak.
7. Might need couple tries to get Jailbreak working. 

I'm thankful to _pwn20wndstuff_ for the unc0ver jailbreak for iOS 12.4!

**Comment by hongsolo9** [comment]
Try 3.5.5! Fast and stable!

**Comment by lewis0917** [comment]
Tried it, it launches but [*] Unable to find kernel's credentials in kernel memory. Fails at step 2 regardless of waiting a few minutes and using airplane mode. Running iOS 11.2.6
