### ISSUE TITLE
OpenSSH - Photo not update

### ISSUE THREAD

**Issue by marcinmielnik** [pwn20wndstuff/Undecimus#1328]
Hi, I have a 'quick question'.
Iphone X, iOS 12.4 - phone reset to default settings, photos stored locally, turned off icloud photo.
Cydia impactor -> unc0ver 3.5.2 - jailbreak done.
OpenSSH installed, WinSCp launched on the computer, wifi connection established.
I go to the folder / private / var / mobile / Media / DCIM / 100APPLE / - I upload photos from a computer
I open photo applications on iPhone - pictures do not appear - why?

**Comment by badger200** [comment]
This is not a bug and has nothing whatsoever to do with unc0ver. The Photos application is not simply enumerating the files in the DCIM 100APPLE folders, it builds and maintains a huge PhotoData/Photos.sqlite database (mine is 3GB) containing all the photos and references between edits (mutations), thumbnails, etc. 

So just adding a file doesn’t work, because if it’s not in the Photos.sqlite database, the Photos app doesn’t know it exists. 

If you want to import files in this manner, julioverne has a repo with a PImport tweak that allows exactly what you want.
