### ISSUE TITLE
can not  use camera

### ISSUE THREAD

**Issue by Born2PushLimits** [pwn20wndstuff/Undecimus#1507]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: xs max
 - unc0ver Version: 3.7

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by Goldstriker208** [comment]
Same with me on iPhone XR on iOS 12.4

Device (please complete the following information):

iOS Version: 12.4
iOS Device: iPhone XR
unc0ver Version: 3.7

Camera app works for a few seconds then freezes up

Here are the links for the screenshots:
https://imgur.com/a/wdGU64p

**Comment by Born2PushLimits** [comment]
@pwn20wndstuff

**Comment by ghost** [comment]
It's not working ... iPhone XR 12.4

**Comment by thu3n** [comment]
Same here! XS-Max 12.1 tried to install simmerdown that someone sugested but didn’t make any difference

**Comment by thecolbster91** [comment]
My camera will start and just blur out and freeze.
I have:
iPhone XS Max 
iOS 12.4
Unc0ver 3.7

![IMG-2709](https://user-images.githubusercontent.com/35181281/65446167-c9979980-de01-11e9-8d1a-a107e6c386ee.JPG)

**Comment by thu3n** [comment]
Seems to be a stabillity issue. I tried re-jailbreak and it does work now

**Comment by elteekta** [comment]
So i saw this on here & have seen a good fix that is working but every so often i have to repeat, its a bit easier than re jailbreaking especially if your device is like mine & takes 10 minutes of down time before i can turn it back on. It goes as follows:
1. Download Newterm tweak on cydia
2. Open the app newterm, and type “su”
3. It will ask for a password, type “alpine”
4. Once it has accepted, type “ldrestart” 

Camera should be working,  EDIT: turns out you dont have to re jailbreak after this fix, just only a temporary fix to the problem itself

Let me know how it goes, im on 12.2 with iphone XS max
