### ISSUE TITLE
Crash and reboot instantly after pressing jailbreak on A12 XS 12.4

### ISSUE THREAD

**Issue by sooxt98** [pwn20wndstuff/Undecimus#1516]

**Comment by h4ckua11** [comment]
If your phone crashes and reboots when you press Jailbreak instantly every time, then just reboot it normally. So press Volume Up and the Power button at the same time und shut it down (Do not force reboot your phone because this will probably not fix it). If it shut down then start it up again. After this your iPhone should jailbreak normal.
