### ISSUE TITLE
FaceID isn’t working on A12

### ISSUE THREAD

**Issue by DonPabloRP** [pwn20wndstuff/Undecimus#1536]
**Describe the bug**
FaceID only **works when unlocking the device**. Once I have to use it for passwords (in Safari) or in other apps (like PayPal), it just doesn’t work. 

**To Reproduce**
1. Enable FaceID
2. Open the ’Settings’-app
3a. Go to ’FaceID & Passcode’
3b. [Enter your passcode]
4. Press ’Set Up an Alternative 
5. Press ’Get Started’
6. You’ll get the output that FaceID is unavailable.

To obtain the error if this method doesn’t work, simply find any app that wants to access FaceID (like PayPal, BankID, AppStore, Dropbox, Lastpass).

**Screenshots**
![D334DA83-98FA-40C8-A792-4C17740BA00F](https://user-images.githubusercontent.com/34809665/65572888-c1f30480-df69-11e9-9b87-369431adefd8.jpeg)
![DE9DEAA0-E932-410D-BAA4-3B793530EE68](https://user-images.githubusercontent.com/34809665/65572890-c28b9b00-df69-11e9-9011-229b820bf34e.jpeg)
![264878F6-3F0B-443E-834C-CA50BDE5ECE7](https://user-images.githubusercontent.com/34809665/65572891-c28b9b00-df69-11e9-9660-e4c41cdb4604.jpeg)

**Device (please complete the following information):**
 - iOS Version:  12.0.1
 - iOS Device: iPhone XR
 - unc0ver Version: 3.7.0~b1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [~] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by realHyperMatrix** [comment]
More on when this issue pops up. This issue is NOT related to the original jailbreak. When you jailbreak, you can install all your apps and respring and everything will work fine. 

HOWEVER...there is one bug that comes up before FaceID is disable (along with FaceID being disabled, all of the “passwords & accounts” features break. So even if it shows you the username for a website above your keyboard, tapping it will not fill in the field). That is that you are unable to REBOOT or SHUTDOWN the iPhone. It will attempt to reboot, but actually crash. After a while, the iphone does a crash-recovery reboot or you will have to do a hard reboot. 

And that is where the trouble lies. Whatever is happening that causes the phone to be unable to reboot/shutdown in a jailbroken state, forever breaks FaceID outside of when you are unlocking the phone. This persists until you restore RootFS and jailbreak all over again, at which point it will again work properly until your phone reboots/shuts down for any reason. 

I attempted to remove all cydia packages and disabled all cydia functions in icleaner pro, but the problem still existed. RootFS is the only way. 

iPhone XS Max on iOS 12.4.

**Comment by miguelr4720** [comment]
Mines is having the same problem too please let me know when its fix this the The Worse Jailbreak I ever seen it's filled with bugs camera

**Comment by DonPabloRP** [comment]
I would like to thank realHyperMatrix for the good and substantial answer. 
So my FaceID will work if I restore RootFS and re-jailbreak?

**Comment by realHyperMatrix** [comment]
Yup. It will work until you reboot/shutdown/crash iOS. Resprings are fine.
Camera still won’t work though.

**Comment by DonPabloRP** [comment]
I restored RootFS and renewed my FaceID.
Then I jailbroke again and whenever FaceID stops working now (because of a reboot/shutdown/crash as you mentioned) I just do an LDrestart (ldrestart -r).

**Comment by realHyperMatrix** [comment]
Thanks for that.  It didn't work for me.  I tried to install the ldrestart
app from Cydia, but it crashed my phone.  Lost my FaceID.  Doing ldrestart
-r though SSH didn't fix it.  BUT....found a better discovery.

After a restart, uncheck "reload daemons" in unc0ver. FaceID keeps working.  Simple as
that.

Now if only there were a way to get the Camera working again.  Haha.

**Comment by DonPabloRP** [comment]
I just reboot and re-jailbreak my device to fix the camera. Are you unable to do that without reloading daemons?

**Comment by realHyperMatrix** [comment]
Regardless of whether reload daemons is on or off, the camera won't work.  It either shows a black screen, or shows an image for about 3 seconds before freezing up.  Seems to be a fairly common issue with this jailbreak as reported on reddit.  I'm surprised it works for you.  Which iPhone do you have?

**Comment by taimaiduc** [comment]
For camera. Follow my steps:
- Reboot
- Open camera
- Close camera 
- Re-jailbreak

**Comment by DonPabloRP** [comment]
I’m using iPhone XR. You?

**Comment by taimaiduc** [comment]
@DonPabloRP 
XS MAX 
You can turn off **Reload demo** as well
![image](https://user-images.githubusercontent.com/10907980/66375720-4026c080-e9d8-11e9-855b-ba40efe786ae.png)
