### ISSUE TITLE
iPhone doesn't turn off unless hard reset.

### ISSUE THREAD

**Issue by KlutchKyle** [pwn20wndstuff/Undecimus#1548]
iPhone won't actually turn off when trying to turn it off. The phone just sits at a black screen with the screen on. Must use hard reset to turn the phone off.

1. Jailbreak with Unc0ver.
2. After respring, press and hold volume up and lock button to open "slide to power off".
3. Slide power off slider.
4. iPhone sits at black screen and will not actually turn off. Back light stays on.
* NOTE: Also reproducible with tweaks that give option to restart phone (Poweroptions)

Device (please complete the following information):**
 - iOS Version: 12.1
 - iOS Device: iPhone XR
 - unc0ver Version: 3.7.0~b1

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Comment by marcowind80** [comment]
Same to me

**Comment by mzxnbcv** [comment]
Same here, ios 12.4 latest unc0ver version 11,6 iphone xs max

**Comment by semiazas** [comment]
XS Max 12.4 w/ 3.7.0b1, so far about 1 out of 3 the phone will eventually hard-reset after a power-off instead of just hanging indefinitely.  When hanging the CPU will get noticeably hot.  Phone remains on the network (via wifi), pingable, and ssh still connects.  Issuing a reboot from shell prompt will result in phone going offline and eventually (after about two-three minutes) hard-resetting.

**Comment by ghost** [comment]
Same to me

**Comment by abigchopstick** [comment]
sometimes it happens and I'm second guessing that it is actually not hanging, just takes too long to shut down because once or twice I waited long enough it eventually shut down or rebooted.

**Comment by 2JayCee** [comment]
Issue fixed on b2 & b3 if I remember.
