### ISSUE TITLE
dpkg_locked

### ISSUE THREAD

**Issue by MegaBloopy** [pwn20wndstuff/Undecimus#1562]
iPhone 7
iOS 12.4 
3.7.0~b1
whenever i install tweaks i get DPKG_LOCKED i have deleted the lock file but i still get this error, any help.  everything online is for electra

**Comment by Romntic** [comment]
try do more than 1 time for restore RootRS

**Comment by MegaBloopy** [comment]
I have tried 5 times to restore rootfs before jailbreaking again

**Comment by Romntic** [comment]
i do by restore rootFS and working with me :) agian
this is a solution also u can do 

first download cydo 
must be u have ifile or Fliza 
http://www.mediafire.com/file/dyxkp9k1cpdjbyz/cydo
put cydo file u downloaded it 
to that path 
 usr/libexec/cydia/

make permstion like that 
https://i.imgur.com/2JLvV6S.png

otherwise if not working u can contact with me thru email
romntic@gmail.com

**Comment by Slingblade7** [comment]
Thanks
