### ISSUE TITLE
Unc0ver doesn't re-jailbreak after reboot and app revoked

### ISSUE THREAD

**Issue by Azas1n** [pwn20wndstuff/Undecimus#1585]
**Describe the bug**
My iPhone 7 plus battery ran out and when i opened it back up i noticed the unc0ver jailbreak app is revoked, so i reinstalled it from https://jailbreaks.fun/ from Everythingapplepro tutorial video, once done i opened the unc0ver app then i saw the button says jailbreak instead of rejailbreak, anyways i pressed it, and it says completed in 30 seconds and my device will now respring, upon pressing the ok button it freezes my whole phone and i need to hard reset it for it to open back up and still be in the unjailbroken state, tried it like 6 times now and even tried to make auto respring in the unc0ver settings with it stucking in the respring black screen, please help me
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.4
 - iOS Device: iphone 7plus gsm
 - unc0ver Version: 3.7.0~b1

**Place an "x" between the brackets if true:**
 - [x ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by cerebral-314** [comment]
click the cog on unc0ver and make sure "load tweaks" in not enabled.  once jailbroken go into cydia and uninstall your last tweak. you can see what you installed last by clicking recent at the top of the "installed" section in cydia. once you have uninstalled the tweak. hard reset your phone or just restart it and re-enable the tweaks in unc0ver options and try to jailbreak.  keep doing this until you find the offending tweak.   Problem solved. for future reference, install crashreporter.  it will usually tell you exactly what tweak caused the error.

**Comment by cerebral-314** [comment]
Oh, one more thing.  Make sure you are not using pirate repos for free, paid for apps.  some legit paid for apps can detect these repos and cause this exact behaivor.   If you must use pirate repos.  always make sure to uninstall the repo after you download the app. and do this before you respring.  Theres a tweak called "Dismissprogress" that allows you to continue browsing cydia even when it tells you to respring after a tweak install. come back here if you have issues. Good luck.

**Comment by acidart** [comment]
I had the same problem a while ago.
I would do the same as cerebrallolzy explains, however if this doesn’t work then you might have to do the same as me and [restore RootFS] in Unc0ver.

I had to try a couple of times before jailbreaked it again, since I was a bit reckless and installed  some packages that wasn’t A12 supported  (iPhoneXR) only moments before the  Unc0ver app was revoked.
So my final solution was to use activate [RestoreFS]  [Reinstall Cydia] & [Re-Install OpenSSH] in Unc0ver and jailbreak it again.

Luckily I didn’t loose anything important since I mainly just experimented with different packages just after the first A12 supported jailbreak released.
—
Just a tip:
I strongly recommend the Cydia Addon • Batchomatic • a that let you create  backups of your entire library of tweaks/apps/addons etc. and store the file both online or offline. 
I use it whenever my device is working accordingly with all the tweaks/addons + I want to use and take a “snapshot” of my device library  incase  I’d end up with the same  or another problem any time in the future. 

If so, all you’ll have to do is reinstall Batchomatic through Cydia and install your backup (.deb) file of your library, which you can create when ever you feel satisfied with the tweaks/addons you wish  on your phone or pad works flawlessly, instead manually installing every package again without needing to memorize every single one.
I recommend making new backups if you want to install several things at once or if you’re installing something you’re not completely sure about, like beta vs. or cracked tweaks and apps.


Good luck.

**Comment by jhern115** [comment]
> click the cog on unc0ver and make sure "load tweaks" in not enabled.  once jailbroken go into cydia and uninstall your last tweak. you can see what you installed last by clicking recent at the top of the "installed" section in cydia. once you have uninstalled the tweak. hard reset your phone or just restart it and re-enable the tweaks in unc0ver options and try to jailbreak.  keep doing this until you find the offending tweak.   Problem solved. for future reference, install crashreporter.  it will usually tell you exactly what tweak caused the error.

exactly how many tries does it take to get into jailbroken state? I get a message saying jailbreak completed but the screen freezes. on beta2

**Comment by cerebral-314** [comment]
Did you make sure "load tweaks" was not checked in the options for unc0ver Version: 3.7.0.b2?

**Comment by jhern115** [comment]
> Did you make sure "load tweaks" was not checked in the options for unc0ver Version: 3.7.0.b2?

It is off but still freezing at completion. 3.7.0b3

**Comment by ZamasuTheGod** [comment]
I got the same issue on my iphone 6 and I just use a old version of uncover 3.5.6 running ios 11 here.
