### ISSUE TITLE
When will jailbreak ios12.4.1 or 13.1

### ISSUE THREAD

**Issue by Skilling-Kiss** [pwn20wndstuff/Undecimus#1597]
Recently,i got a new device,but it's ios 12.4.1,no jailbreak no iphone,so i'm looking forward to getting a new version for ios 12.4.1 or 13.1.The sonner,the better.I'm waitting you!Ths.

**Comment by AnakinSkywalkerVader** [comment]
I wouldn't get ur hopes up anytime soon - by the admission of pwn himself 12.4.1 is unjailbreable using undecimus which is his jailbreak tool! At this point i'm really starting to wonder if staying on 12.4.1 is a mistake. 

U should Be happy tho  - at least u weren't forced to upgrade to ios 12.4.1 by Apple & iTunes from an awesomelyt jailbroken iOS 12.4 on an old iPhones 5S 64 bit that by nothing short of a miracle finally had got BOTH cydia & sileo to function on my iPhone & coexist right b4 it went into a total irrecoverable black screen crash which left no choice but to have bricked iPhone or restore/update tic 12.4.1 since Apple had stop signing 12.4 about 10 days b4 this happened 😞😡

**Comment by Skilling-Kiss** [comment]
Haha,i give up waitting for it,so i got a new Android phone,it's Samsung S10+,perhaps someday i'll back to ios,but it will not be soon,because Notch is so ugly for me,i can't stand its screen,and it makes Apps so uncomfortable.I'm waitting a full screen,true full screen.

**Comment by ninesthree** [comment]
@Skilling-Kiss check pwn’s twitter bro 12.4.1 will be out very soon
