### ISSUE TITLE
<solved>unc0ver can not be installed my ipad pro 1st gen

### ISSUE THREAD

**Issue by veteransdr** [pwn20wndstuff/Undecimus#1604]
![20191102100605](https://user-images.githubusercontent.com/37284730/68072123-739b0780-fd58-11e9-9b18-55244be8ae9a.jpg)

This happen every 2nd time I installed unc0ver. And when I got this, there was next version of unc0ver  untill now. But not today... finally.

I did revoke, delete apple id on impactor.
I tried install with jailbreaks.fun and ignition.fun. 

But not working. 

Please help.

**Comment by veteransdr** [comment]
OMG... i solved this issue. 
![20191102102445](https://user-images.githubusercontent.com/37284730/68072337-076dd300-fd5b-11e9-8e1f-4ea99122934e.jpg)


I guess maybe there is missing file inside of ipa. 
So I download agian, and it not same as previous. 
Both of them are downloaded after last release date. But as you can see... size are not same.

Hope this is helpful someone has same issue. 

Thanks, all.

**Comment by badger200** [comment]
> OMG... i solved this issue.
> ![20191102102445](https://user-images.githubusercontent.com/37284730/68072337-076dd300-fd5b-11e9-8e1f-4ea99122934e.jpg)
> 
> I guess maybe there is missing file inside of ipa.
> So I download agian, and it not same as previous.
> Both of them are downloaded after last release date. But as you can see... size are not same.
> 
> Hope this is helpful someone has same issue.
> 
> Thanks, all.

I had a similar issue: ever since the big 3.7.0, I have suffered chronic instability on both my iPhone 6 and iPad Pro 9.7” (1st gen 2016) on 12.4 where they only run smoothly for ~2-3 days before they will consistently become sluggish and eventually freeze (until either me or the watchdog timer automatically resets the device). And my use cases for the two devices are quite different. I barely use my iPhone, the iPad is used very heavily every day.

I could swear I enjoyed a full week of uptime in the 3.5 and 3.6 releases of unc0ver. (I wish I had documented this, in retrospect, so I could know for sure if this was fact, or just foggy memory.)

So I tried going back to 3.6.2b+1 or whatever it was called, and I noticed 3.6.3 ALSO identifies itself as 3.6.2b+1 in the unc0ver app? (I’m 99% sure I used official releases downloaded right here from github). EXCEPT there’s a substantial difference in file size, like 32MB vs 35MB, and even after unpacking both and comparing folders, I still was left inconclusive as to what was actually different. 

I can’t fathom why any developer would ever release a substantial +3MB change to a 32MB release and NOT increment the version (unless it was an accidental oversight)...

I’m on 3.8.0b1 now and still suffer the same poor stability beyond 24-48-72hrs on both devices. I almost wish I could go back to whatever versions all my packages/tweaks were during 3.5/3.6 but I don’t know any way to do that.
