### ISSUE TITLE
Hotspot dont work after jailbreak

### ISSUE THREAD

**Issue by sLi1996** [pwn20wndstuff/Undecimus#1607]
As in titel mentioned after the jailbreak is successfully installd, my hotspot stop working.
Just for the test i did restore my phone to default and the hotspot works as usual.

 - iOS Version: 12.4
 - iOS Device: iphone xs max a12
 - unc0ver Version:  v3.7.0 b3 (latest)

Best Regards

**Comment by cerebral-314** [comment]
What might be happening is the device you are connecting could be going into idle mode and disconnecting itself.  Another problem could be the use of power saving tweaks, like smart low power mode tweak. Enabling these type of tweaks can cause this type of behavior with your hotspot.

**Comment by STIXXXXXX** [comment]
Reboot - jailbreak with Reload System Daemons disabled - worked for me.
XS 12.4 unc0ver 3.7.0b3

**Comment by palxex** [comment]
@STIXXXXXX thanks for your mention, this resolved my USB-Tethering problem and universal clipboard problem, also only occurs after jailbreak with ReloadSystemDaemons on, toggle if off resolved them.

**Comment by badger200** [comment]
> @STIXXXXXX thanks for your mention, this resolved my USB-Tethering problem and universal clipboard problem, also only occurs after jailbreak with ReloadSystemDaemons on, toggle if off resolved them.

I wonder what the Root Cause is/was? If you’re interested, I would begin diagnosis using dmesg and syslog commands to monitor for clues of what’s failing, particularly if you can trigger the failure (perhaps by copying to clipboard, or plugging in your USB tether) and then immediately check both those logs. 

The BigBoss tool “oslog” is even more powerful, it displays a real-time scrolling syslog. If you know or suspect the problematic process, you can use “oslog -p XYZ” (where XYZ is either the process name like assetsd, SpringBoard etc., or a PID) to limit the oslog activity to only that process. 

If you want even more data, you can add —debug which enables verbose logging. 

Personally I check my dmesg and syslog at least once a day just to keep an eye on things, and more frequently when having issues with anything. After a while, you become skilled in identifying what is normal noise vs abnormal (smoking gun clues). 

The downside of jailbreaking is many tweak authors don’t code properly for max compatibility and safety, they only code the minimum to achieve functioning on their device(s). This leads to many and often-subtle bugs that can be difficult to trace back to their culprit/origins. Most common are tweaks causing SpringBoard crashes (uncommanded resprings).
