### ISSUE TITLE
[Help] unable to repair system (launchctl)

### ISSUE THREAD

**Issue by Riggola** [pwn20wndstuff/Undecimus#1625]
Hello,
I recently updated some tweak from sam repo and everything was ok during install, but after i noticed some problem with app and then i downgraded jb resource and now im stuck in cydo error code 2 and im unable to do anything.
What i can do? if you need more info just let me know what you need!
Thank you

![IMG_9727](https://user-images.githubusercontent.com/1492661/69656634-308f3400-1079-11ea-8fdc-275d583a68d6.PNG)
![IMG_9728](https://user-images.githubusercontent.com/1492661/69656635-308f3400-1079-11ea-931d-4f03b7beda01.PNG)
![IMG_9721](https://user-images.githubusercontent.com/1492661/69655075-21f34d80-1076-11ea-972d-6902edf496ff.PNG)
![IMG_9725](https://user-images.githubusercontent.com/1492661/69655076-21f34d80-1076-11ea-88db-87c883ee5137.PNG)
![IMG_9723](https://user-images.githubusercontent.com/1492661/69655077-21f34d80-1076-11ea-8a57-1c0ba1d363db.PNG)
![IMG_9724](https://user-images.githubusercontent.com/1492661/69655078-21f34d80-1076-11ea-8cff-91726e7aa25a.PNG)
![IMG_9722](https://user-images.githubusercontent.com/1492661/69655079-228be400-1076-11ea-9422-edef433baf7e.PNG)

**Comment by Riggola** [comment]
nevermind i just rootfs and reconfiguring everything

**Comment by Rigolas** [comment]
Can you show me what you did? I have this exact same problem with the same Cydia error code.

**Comment by Riggola** [comment]
I had the same issue today with an iPad Air 2 both when trying to update/install the essential packages, the first time it failed, after rootfs it failed again: when opening Cydia the first time and update/installing the essential package (completely fresh jailbreak).
After the third try it finally manage to install everything without error

**Comment by Rigolas** [comment]
Ok, I'll try it out.

**Comment by Riggola** [comment]
Yeah they are some kind of core package and automatically get in queue but if it fail installing them you will get in a cydo error 2 loop

**Comment by Rigolas** [comment]
I'm pretty much stuck in a cydo error 2 loop every time I install packages

**Comment by Rend0e** [comment]
I had the same error: dpkg: warning: 'launchctl' not found in PATH or not executable
dpkg: error: 1 expected program not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
E: Sub-process /usr/bin/dpkg returned an error code (2)

I solved it by installing Launch Daemon Controller (launchctl) via terminal:
Download https://apt.bingner.com/debs/1443.00/launchctl_22-1_iphoneos-arm.deb to Filza.
Open terminal and enter:
CD /var/mobile/Documents
dpkg --force-all -i launchctl_22-1_iphoneos-arm.deb

**Comment by Riggola** [comment]
I tried it too but it given the error path ect, but not with the parameter “—force-all” since I didn’t know about it

Edit: but wait I just read the error, we didn’t have the dpkg error, we had cydo error code 2

**Comment by Rigolas** [comment]
I tried erasing all content on the iPhone (yes, I did make a backup before erasing) and starting up as a new iPhone. I installed unc0ver and ran the exploit, then tried to install packages on Cydia, but the same error code pops up. Right now, I'm just restoring to my backup, staying at my current condition.

**Comment by Rend0e** [comment]
> I tried it too but it given the error path ect, but not with the parameter “—force-all” since I didn’t know about it
> 
> Edit: but wait I just read the error, we didn’t have the dpkg error, we had cydo error code 2

It’s the same error. I think the problem is that new essential cydia updates is causing cydia to have trouble updating/installing ‘Launch Daemon Controller’ (launchctl) which is showing on cydia as cydo error code 2. 

If you check the log on the unc0ver app it says:
 dpkg: error: 1 expected program not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
E: Sub-process /usr/bin/dpkg returned an error code (2)

Which means that ‘Launch Daemon Controller’ (launchctl) is missing and causing problems. To fix it you have to forcibly install Launch Daemon Controller’ (launchctl) via terminal with dpkg --force-all -i launchctl_22-1_iphoneos-arm.deb

Instructions:
Download https://apt.bingner.com/debs/1443.00/launchctl_22-1_iphoneos-arm.deb to Filza.
Open terminal and enter:
CD /var/mobile/Documents
dpkg --force-all -i launchctl_22-1_iphoneos-arm.deb

Restoring rootfs may not fix the problem because cydia essential updates will require you to install the problematic Launch Daemon Controller’ (Launchctl) which would cause the whole problem again.

**Comment by Rend0e** [comment]
I believe this has been fixed
https://mobile.twitter.com/sbingner/status/1201381940646924290
