### ISSUE TITLE
iPad Air update cydia ruined whole package manager

### ISSUE THREAD

**Issue by palxex** [pwn20wndstuff/Undecimus#1626]
**Describe the bug**
On fresh-jailbroken iPad Air, open new installed Cydia, it will update and report Cydia installer needs upgrade; then after upgrade, it will fail and complains 'Sub-process /usr/libexec/cydia/cydo returned an error code(2)'; after that fail, every package installation will fail and get that complain, restore rootfs and rejailbreak does not changes anything.

**To Reproduce**
1. Restore Rootfs, rejailbreak
2. Open Cydia, saw 'upgrades', press 'essential'
3. Upgrade fail and cydo complains
4. Every new package install saw the complain, even the jailbreak progress with "Reinstall Cydia" toggled

**Device (please complete the following information):**
 - iOS Version: iOS 12.4
 - iOS Device: iPad Air
 - unc0ver Version: 3.7.0b3

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
My iPhone XR upgraded well, also on 12.4 3.7.0b3.
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
The mentioned re-jailbreak log, with reinstall cydia on:
[unc0ver.log.txt](https://github.com/pwn20wndstuff/Undecimus/files/3907922/unc0ver.log.txt)

**Comment by palxex** [comment]
Resolved myself by splitting the batch update.
1. Open Cydia, ignore all update.
2. Install all other updates except cydia, several respring.
3. Install Cydia installer update STANDALONE. After upgrade done press Close Cydia
4. Reopen Cydia, it crashed
5. Reopen Cydia, it finally upgraded to 1.1.32-b23, and cydo not complains.
Seems a cydia 1.1.32~b21 problem, not able to batch upgrade with part of UIKit Tools/DarwinTools/debugserver/jbctl/Launch Daemon Controller/JailbreakResources/ldid/bash( all package names I installed standalone ).

**Comment by alexmaten** [comment]
> Resolved myself by splitting the batch update.
> 
> 1. Open Cydia, ignore all update.
> 2. Install all other updates except cydia, several respring.
> 3. Install Cydia installer update STANDALONE. After upgrade done press Close Cydia
> 4. Reopen Cydia, it crashed
> 5. Reopen Cydia, it finally upgraded to 1.1.32-b23, and cydo not complains.
>    Seems a cydia 1.1.32~b21 problem, not able to batch upgrade with part of UIKit Tools/DarwinTools/debugserver/jbctl/Launch Daemon Controller/JailbreakResources/ldid/bash( all package names I installed standalone ).

Thank you so much! After a few days looking for a solution, finally one worked for me! Thanks!

**Comment by alexmaten** [comment]
>Resolved myself by splitting the batch update. ...

@palxex 

Thank you so much! After a few days looking for a solution, finally one worked for me! Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by palxex** [comment]
@alexmaten Glad it helps:)

**Comment by Rend0e** [comment]
I think the problem is that new essential cydia updates are causing cydia to have trouble updating/installing ‘Launch Daemon Controller’ (launchctl) which is showing on cydia as cydo error code 2.

If you check the log on the unc0ver app it says:
dpkg: warning: 'launchctl' not found in PATH or not executable
dpkg: error: 1 expected program not found in PATH or not executable 
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin 
E: Sub-process /usr/bin/dpkg returned an error code (2)

Which means that ‘Launch Daemon Controller’ (launchctl) is missing and causing problems. To fix it you have to forcibly install Launch Daemon Controller’ (launchctl) via terminal or ssh with dpkg --force-all -i launchctl_22-1_iphoneos-arm.deb

Instructions: 
Download https://apt.bingner.com/debs/1443.00/launchctl_22-1_iphoneos-arm.deb to filza
Open terminal (or ssh) and enter:
su
cd var/mobile/Documents
dpkg --force-all -i launchctl_22-1_iphoneos-arm.deb

Restoring rootfs may not fix the problem because cydia essential updates will require you to install the problematic ‘Launch Daemon Controller’ (Launchctl) which would cause the whole problem again. So you must forcibly install Launch Daemon Controller to completely fix the problem.

**Comment by palxex** [comment]
@Sekkio thanks for your analysis!
From my experience, the launchctl deb does not have problem, can be installed well standalone, without force.
It only fail when upgrading with Cydia Installer, same time. Which may refer to cydia beta bug, or transactional problem in apt system.
A quick&dirty solution is make a new unc0ver release, includes latest essential packages.

**Comment by Rend0e** [comment]
This problem has been fixed 
https://twitter.com/sbingner/status/1201381940646924290?s=21

**Comment by palxex** [comment]
Thanks @Sekkio mentioned. 
Verified updated package uses similar policy, deny Cydia Installer and jbctl upgrade in one transaction. Closing due to fixed.
