### ISSUE TITLE
Restore rootFS bricks FaceID

### ISSUE THREAD

**Issue by Soifam** [pwn20wndstuff/Undecimus#1665]
**Describe the bug**
After using restoreFS option, faceID stopped working. When trying to re-setup faceID, it just says "move up" or "move down". Sometimes it shows a generic error "FaceID isn't available". 

Tried everything:
-Restart
-Rejailbreak
-Restore
-DFU restore (+icloud backup)
-OTA update

I'm not the only one; just Google "reddit jailbreak rootfs faceid", tens of results show up. 
In some cases they associate the issue with having had a screen repair in the past. It's not my case.

**To Reproduce**
1. Do restore rootFS
2. FaceID magically stops working

**Device (please complete the following information):**
 - iOS Version: iOS11 (did rootFS in this version), faceID continues not working on iOS12 and iOS13.
 - iOS Device: iPhone X
 - unc0ver Version: don't remember

**Place an "x" between the brackets if true:**
 - [ ?] this is a bug others will be able to reproduce
 - [ x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ xxxxxxx] this issue is present after a rootfs restore
 - [ ?] this issue is present on the latest version of unc0ver

**Comment by ozgureylem** [comment]
I have the same issue. I used to do rootfs frequently on 4.3.1 with no problems until I got my screen replaced at Apple. Approximately 2 months after the screen replacement, first time I did Rootfs gave me faceid error. Since then I tried reset, DFU restore, IOS update (13.5) unc0ver updates until 5.2.0 and nothing so far seems to be getting it to work again. 

What I have noticed is; flood illuminator isn’t as bright as it was before (I used to see it brighter when I was recording a video of my screen with another phone) 

I’m also very sure that there are many people who have their faceid bricked. And I am hoping that someday there will be a software fix for this. Looking for for it
