### ISSUE TITLE
long respring after Jailbreaking

### ISSUE THREAD

**Issue by PwnedC99** [pwn20wndstuff/Undecimus#1698]
**Describe the bug**
If you Jailbreak your device, and wait until it resprings you'll encounter a really long respring time (30 seconds) which was not the case in the first private beta of Unc0ver.

**To Reproduce**
1. Jailbreak
2. Wait until it resprings.

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone11,6
 - unc0ver Version: Latest 4.0.0

**Place an "x" between the brackets if true:**
 - [ X ] this is a bug others MIGHT be able to reproduce
 - [ X ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ X ] this issue is present after a rootfs restore
 - [ X ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by ogjuggy** [comment]
-IOS Version: 13.1.3
-IOS Device: iPhone 11
-unc0ver Version: 4.0.0

When jailbreaking, 
if I see "Jailbreak completed 30/30"
The phone will either freeze when pressed on OK
or
The phone will be put into a long bootloop when pressed OK.
^^ This bootloop will not end up successfully respringing the phone.

**Comment by gabe-lucas** [comment]
**Describe the bug**
Upon jailbreaking successfully the app freezes when exiting or hangs in a respring of the device and eventually reboots.

**To Reproduce**
Steps to reproduce the behaviour:
1) Click Jailbreak
2) Tap okay.

**Device (please complete the following information):**

iOS Version: 13.2.3
iOS Device: iPhone11,6
unc0ver Version: Latest 4.0.0
Place an "x" between the brackets if true:

[ X ] this is a bug others MIGHT be able to reproduce
[ X ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
[ X ] this issue is present after a rootfs restore
[ X ] this issue is present on the latest version of unc0ver
**Logs**
[https://hastebin.com/ujosuluvus.makefile](https://hastebin.com/ujosuluvus.makefile)

**Comment by dablackmage** [comment]
Model: iPhone XR
IOS Verison: 13.2 beta
Verison: unc0ver 4.0.0


The same issue is happening on my IPhone XR running 13.2. Make it all the way to jailbreak complete and phone completely freezes. 30/30

**Comment by vovtokare** [comment]
iPhone XR iOS 13.1.2
