### ISSUE TITLE
11.4 beta 3 mtp exploit not working

### ISSUE THREAD

**Issue by jjj122** [pwn20wndstuff/Undecimus#17]
All 15F5601e 11.4 beta 3 devices are not working for the multipath exploit

**Comment by Samgisaninja** [comment]
Are you using the latest (RC6 as of the time of this comment) version of unc0ver?

**Comment by jjj122** [comment]
Yes, and it is still currently not working

**Comment by Samgisaninja** [comment]
ok, does it show any progress (does it get past 1/48), or does it reboot while still showing 1/48? if it shows progress, what's the last number you see? does it show any error messages? what is the error code and line number of the error?

**Comment by jjj122** [comment]
There is nothing it shows but failed,reboot but it does not reboot the device and it stays on the screen it does not freeze but when exited it just says jailbreak again

**Comment by Samgisaninja** [comment]
ok, this is because the multipath exploit is failing. Since this is a less common version, I'm going to leave this issue open, but this issue can probably be fixed with patience.

make sure you wait ~1-2 minutes before jailbreaking, use airplane mode, and disable Siri and background app refresh. Even then it's not going to work 100% of the time, but it might help.

Please close this issue if you get it working. In the meantime, we'll look out for other reports of this issue and look into them if we get any.

**Comment by yaf3i** [comment]
mptcp is patched on 11.4b1/2/3 
(correct me if i am wrong)

**Comment by Samgisaninja** [comment]
No, you're right lol. I had it confused @yaf3i 

@jjj122 Use VFS, multipath is patched on 11.4 betas
