### ISSUE TITLE
Anti-JB for outlook and bancoposta...

### ISSUE THREAD

**Issue by ghost** [pwn20wndstuff/Undecimus#1706]
**Describe the feature you'd like**
Anti-Jailbreak detection

"Bancoposta" (a banking app refuses login attempts if you are jailbroken)
"Outlook" (Crashes when you try to launch it under jailbreak).

**Describe alternatives you've considered**
I Tried any Anti-JB Detection tweaks, they all failed...
**Additional context**

**Comment by stohle** [comment]
Most likely your banking app looks for any files related to jailbreaking. Most of the anti jailbreak tweaks out there only disables tweak injection into the banking app. There are no workarounds for this at the moment. My norwegian banking app does this. It doesnt even care about jailbreak related processes. It looks for substrate/substitute. If i can somehow move or rename those two files without breaking the whole jailbreak then my banking app would work. I cant patch the app itself since the code is obfuscated as hell and nothing makes sense.

Atleast your banking app starts up. my app just crash on startup. I´ll look into your app and see if i can remove the JB checks on startup if you can send me the .ipa. Cant find it on app store

Regarding Outlook. Install Flex 3 and search for outlook and you´ll find a patch for that.

**Comment by miguelr4720** [comment]
am having the same problem with Outlook every-time i open it crashes microsoft must it blocked it flex3 doesn’t work for me neither

**Comment by miguelr4720** [comment]
![FF25649B-AAA3-451B-AB76-1F9E6645CBAD](https://user-images.githubusercontent.com/36649261/74617316-83b5d780-50fa-11ea-8b4e-54b581fc56a8.png)
![Uploading F8602E2A-C430-48BE-AADB-87A019C7A399.png…]()

**Comment by miguelr4720** [comment]
its crashing on mines too pwn please fix outlook

**Comment by stohle** [comment]
This has nothing to do with pwn so dont @ him for that. Its up to us to figure out how to bypass the jailbreak detection in apps

**Comment by miguelr4720** [comment]
thanks for letting me know and hope you find the fix soon @stohle

**Comment by miguelr4720** [comment]
i try flex 3 did not work

**Comment by ghost** [comment]
What annoys me, both applications do work if you reboot and launch them in non-jailbreak mode, and both works without issues, soo is definitely something checking for a jailbreak that makes these not work.

**Comment by stohle** [comment]
Since Outlook works in a non jailbroken state then that tells me that Outlook's jailbreak check is either to check if certain jailbreak processes are running or tries to write to a dir you wouldnt have access to without jailbreak, for example root directory.

If there are server side checks in outlook to check if the app has been tampered with then this is completely impossible to fix.

**Comment by miguelr4720** [comment]
> What annoys me, both applications do work if you reboot and launch them in non-jailbreak mode, and both works without issues, soo is definitely something checking for a jailbreak that makes these not work.

yes mate please find a fix soon thanks for the hard work

**Comment by miguelr4720** [comment]
outlook doesn’t work if you login in setting and add to mail email wont load? inside folders inside inbox in the Mail App on the Phone neither

**Comment by naliferopoulos** [comment]
This has nothing to do with unc0ver. Most banking and personal data handling applications come with jailbreak detection out of the box to protect users from attacks. Unc0ver, and any other jailbreak utility for that matter, exploits a bug in the kernel code to escalate privileges and patch the system, install Cydia and substrate, along with a bunch of other tasks (you can see them in the source code of unc0ver). 

Now applications such as Outlook include code to attempt to check whether they are being run on a jailbroken device, such as Cydia and/or substrate being installed, process listing, hooking detection by viewing stack traces, etc. In case such a detection happens, the application refuses to run. 

In order to attempt to fix those issues, there are two ways of approaching this. Either detecting and removing the checks statically (that is, without the application being run) which is hard to do because the code is probably obfuscated, or by dynamically instrumenting it and blocking the calls it uses to identify the jailbreak, using Substrate, Frida, or ltrace for example. 

For popular applications such as Outlook, a tweak that patches Jailbreak detection will most likely be developed by the community. If you can't wait, or are willing to contribute, you can starting inspecting the application yourself! Good luck! :)

**Comment by stohle** [comment]
@naliferopoulos can confirm that Outlook is obfuscated. Well this patch is beyond my coding skills

**Comment by mau5atron** [comment]
@marcocorriero Please close this thicket. It is unrelated to the jailbreak.

**Comment by miguelr4720** [comment]
HAS ANYONE FOUND A FIX AND RESOLUTION FOR THIS??? :(

**Comment by miguelr4720** [comment]
https://github.com/stohle
LIKE EVERYONE IS HAVING THE PROBLEM IS THERE ANY FIX FOR THIS

**Comment by andre104623** [comment]
How many times are you going to post this these apps have jailbroken Protection and will never work while your jailbroken I’m sorry if some people don’t understand this but yea you want to use those apps reboot use unjailbroken and then after your done re-jailbreak and if you can’t deal with that then update lose your jailbreak and use all your apps simple as that close thread

**Comment by miguelr4720** [comment]
Outlook doesn’t work neither been unjailbroken.

**Comment by andre104623** [comment]
You would have to restore rootfs everytime you wanted to use them then and lose all your tweaks and Cydia I told you before use Apple mail and if you don’t want to restore rootfs and lose your jailbreak if you think outlook is worth it (It’s not)

**Comment by andre104623** [comment]
A lot of people have this problem with banking apps and they are there for a reason some people where stealing money when limerain was released and started this (the only other boot loader exploit ever released

**Comment by andre104623** [comment]
Like checkm8

**Comment by andre104623** [comment]
Fact is no workaround no fix and there probably never will be only the really popular Social apps get fixes like that if they’re even possible

**Comment by andre104623** [comment]
Go on google and you can pull a list up of blacklisted apps in jailbroken mode

**Comment by andre104623** [comment]
And like the guys said above This has absolutely nothing to do with the exploit the jailbreak And cannot be fixed by the developer of uncover so there is no point for it to be here since it can’t be fixed by pwn

**Comment by TimTaler84** [comment]
Install AppStore++ from Cydia! Then Downgrade your Outlook-Version to 4.20.0 or 4.19.0 and it worx fine!

**Comment by stohle** [comment]
@marcocorriero A temporary workaround is ofc to do as Tim stated above. Confirm that 4.19.0 works without any patches.

I am working on a patch for the latest version 4.26.0. Im not gonna use alot of time on this because Microsoft will just release a new update as soon as i release the patch and then its broken again. Just stay on 4.19. The difference between 4.19 and the newest is nothing else other than bug fixes.

@marcocorriero close this after reading this since this has nothing to do with unc0ver

**Comment by adamturbo** [comment]
Found an article about a new Jailbreak detection app called FlyJB. I tried it and it works on the latest Outlook version.

![3FE75423-BB40-4AEB-9371-26992BF08090](https://user-images.githubusercontent.com/61048726/77218059-6abd9d80-6b62-11ea-922a-f55602db2755.jpeg)


https://piunikaweb.com/2020/03/12/want-to-bypass-jailbreak-detection-flyjb-makes-it-possible/
