### ISSUE TITLE
Unable To Exploit Kernel | iPad 10.5 IOS 13.3

### ISSUE THREAD

**Issue by souder14** [pwn20wndstuff/Undecimus#1799]
Im unable to jailbreak my ipad pro 10.5 i get the unable to exploit kernel error. 
![2065F758-2C6A-48C6-8089-50A6AEA05784](https://user-images.githubusercontent.com/1723741/75283485-fb61c180-57e0-11ea-8a71-5ea4253ec840.png)

**Comment by sanderkees** [comment]
Have tried rebooting your iPad and jailbreaking with Airplane mode on.
Once you’re device is back up after jailbreaking you can enable WiFi again

**Comment by stefzouille** [comment]
me too iphone 8 in 13.3.
I restart and airplane mode but nothing to do it does not want

**Comment by souder14** [comment]
I figured it out. Disable Siri

**Comment by StartNext-zz** [comment]
Have the same problem. Unfortunately I rebooted my IPad, like it was mentioned in the error. After the reboot I wanted to re-jailbreak. Since then Unc0ver 4.2.1 and Cydia immediately crash. Siri was always disabled. I tried to reinstall (with and without Airplane mode) and reboot several times now without success.

**Comment by souder14** [comment]
In order for me to get it to work.

1) Restart your device
2) Completely disable siri
3) turn on airplane mode

The jailbreak should work now

**Comment by StartNext-zz** [comment]
> In order for me to get it to work. 1) Restart your device 2) Completely disable siri 3) turn on airplane mode The jailbreak should work now
> […](#)


Did all of the above. Unc0ver 4.2.1 immediately crashes when i touch the icon. Everything work fine before updating from 4.1.1 to 4.2.1

**Comment by souder14** [comment]
Seems like another bug was introduced in 4.2.1.

**Comment by souder14** [comment]
They might need time to work out a few kinks as they just introduced the A9
- A11 jailbreak in 4.2.1.

**Comment by StartNext-zz** [comment]
I read that in some rare cases this can happen and the only fix is to reset your IPad. Not sure how to reset without being forced to update to 13.3.1. In the preceding versions you could update and re-jailbreak without any error messages or reboots. They clearly made some modifications in 4.2.1

**Comment by andre104623** [comment]
I think you need to delete the update package in settings your iPad probably downloaded 13.3.1 and you need to delete it reboot the phone and try again

**Comment by stefzouille** [comment]
Hi,
so for me it worked:
go to the top right of the unc0ver menu at the bottom press automaticly select exploit and clean diagnostic data.
then deselect load tweak then press jailbreak.
it should reboot, repeat the same manipulation by handing load tweak, it should jailbreak normalent.tester on 8 and 11 ..

**Comment by stefzouille** [comment]
And just With plane mode...

**Comment by gamingnation1** [comment]
After I did a hard reboot
It finally worked
So maybe try that. It worked for me.........

**Comment by jasons-open-repo** [comment]
Yes, that happens to unc0ver <=4.2.1 quite often on A11 and lower. Currently, the only workaround is rebooting and trying again over and over til it works, I’m pretty sure pwn20wnd is very aware of this issue and it might be fixed on the upcoming 4.3.0 update. (Which fixes 20+ bugs)
My suggestion to workaround this bug is rebooting and trying until it works, if your patience, wait till the unc0ver 4.3.0 update and trying. (P.S if your tried of buggy unc0ver, you could always unjailbreak by disabling everything in the settings except “Refresh icon cache” and “Restore RootFS” and clicking the Jailbreak button (Which will be renamed to Restore RootFS after changing settings)

**Comment by clip** [comment]
I have the exact same problem too. Except I’m on a IPhone XS.
