### ISSUE TITLE
Unable to view Battery performance

### ISSUE THREAD

**Issue by dinol1187** [pwn20wndstuff/Undecimus#1801]
**Describe the bug**
This Bug is present again in the latest Unc0ver update. (4.2.0)

**To Reproduce**
1. Go to '.settings..'
2. Click on '.battery...'

**Screenshots**

![2FA900D4-C2A4-44A2-923C-1E38673AF8A7](https://user-images.githubusercontent.com/40964402/75306828-274c6980-5818-11ea-9e31-eb2abbfc2bfc.jpeg)

**Device (please complete the following information):**
 - iOS Version:13.3 
 - iOS Device: iPhone XR
 - unc0ver Version: 4.2.0

**Place an "x" between the brackets if true:**
 - [X] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by metriics** [comment]
I have this issue as well.

iOS Version:13.3
iOS Device: iPhone Xs
unc0ver Version: 4.2.0

The issue is not present when Load Tweaks is toggled off, @dinol1187 can you test this as well? Maybe we have a common tweak causing this issue. I'll post my tweak list below.

Tweaks installed are (including defaults):
AppList
AppSync Unified
Arkrome
Asteroid
AudioSnapshotServer
Barmoji
BigBoss Icon Set
ColorFlow 5
Cydia Installer
Cydia Translations
HomePlus Beta
iPhone Firmware (/sbin)
Jailbreak resources
libCozy
libCSColorPicker
libCSPreferences
libmitsuha
MTerminal
Saw
shuffle
SnowBoard
StatusVis
Substitute
Substitute Support Package
Substrate Safe Mode
System Memory Reset Fix
Winter Mode for Apple Watch

Let me know if you have any of the same tweaks. If all we have in common are the default packages then the issue is likely something to do with those or unc0ver itself. If we do have common tweaks we should uninstall them one by one to check.

Edit: post any tweaks you have in common so I can uninstall them one by one to test

**Comment by dinol1187** [comment]
It’s not a tweak causing the issue. When you tick “load tweaks” what your doing is disabling tweak injection there is a bug in the latest unc0ver build causing the issue. I ended up downgrading unc0ver to 4.1.1 and the issue is not present and all is well again.

**Comment by trungking** [comment]
This happend with checkra1n too and should be fix
In the mean time, you can install tweak powerlogHelperdFix to fix this

**Comment by hen6e** [comment]
I am having same issue.

iOS Version:13.3
iOS Device: iPhone XR
unc0ver Version: 4.2.0

**Comment by z-x-f** [comment]
I am having same issue.

iOS Version:13.3
iOS Device: iPhone XR
unc0ver Version: 4.2.0

**Comment by z-x-f** [comment]
wow，4.2.1 fixed it.
hahaha

**Comment by dinol1187** [comment]
Thanks pwn2ownd your latest update fixed this issue!
