### ISSUE TITLE
Jailbreak to reboot!

### ISSUE THREAD

**Issue by BotClancy** [pwn20wndstuff/Undecimus#1817]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**
1. Go to Unc0ver jailbreak
2. Click on Jailbreak!
4. Enjoy your reboot

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.0.1
 - iOS Device: XS Max
 - unc0ver Version: 4.2.0

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.
Happens on step 20 of the jailbreak process

**Comment by mau5atron** [comment]
@BotClancy You should be using this instead. https://chimera.sh/

**Comment by BotClancy** [comment]
@mau5atron That was hilarious!

**Comment by Hamlock-Maneuver** [comment]
12.0.1   What are you doing bro?  you using the wrong version of unc0ver.   LOL Why does nobody do any research anymore?  How do you expect to get anything done this way?

**Comment by suprstarrd** [comment]
As stated above, unfortuntately 12.0.1 does not work with unc0ver 4.x.x. You'll need to use unc0ver 3.8.0 instead.

**Comment by BotClancy** [comment]
@jbmagination that’s what I found out sorry forgot to close this thread

**Comment by BotClancy** [comment]
@jbmagination how can I get install the ipa for 3.8.0 then? I have the ipa file saved but I don’t have the option of alt store due to my version and impactor doesn’t work anymore

**Comment by suprstarrd** [comment]
https://github.com/pwn20wndstuff/Undecimus/releases/download/v3.8.0%25b1/Undecimus-v3.8.0.b1.ipa

To clarify, do you have macOS or do you use Windows?

**Comment by suprstarrd** [comment]
Ah wait, you have the IPA saved. Ignore the link then.

**Comment by BotClancy** [comment]
@jbmagination I have a windows 64 bit

**Comment by Hamlock-Maneuver** [comment]
Google search a program called Altserverpatcher.exe   What this does is trick the AltStore Windows installer into installing any .IPA you want, Instead of the actual Altstore app.   The way it works is you install the altstore on your pc. You will see this little grey diamond down by the clock.  Thats the Altserver.  At the point, you need to open the Altserverpatcher.exe and point it to the IPA you want to install (this being unc0ver 3.8.0).  Now the tricky part here is you need to have the file in an http style URL.  This is what I did instead of using some other website. http://127.0.0.1:3377/Undecimus-v4.3.1.ipa  As you can see this is an internal ip address hosted on my own computer.
I did this by using Windows Internet Information services (ISS) manager app. You can google how to set this up.  Its very easy.  Ok now that you have the address.  You enter this into the Altserverpatcher.exe as a "Custom IPA Link" and click patch.  This will cause the Altserver running down by the clock to crash, so you will need to turn it back on. Now plug your phone into your computer, and click the altserver down by the clock.  Click install Altstore , and you will see your phone, click your phone. This will now bring up a prompt for the Apple ID you want to use for the certificate. Once you enter it, It should go through a short proccess of installing whatever app you choose.  (unc0ver 3.8.0).  Once you see uncover on the phone, go into setting, general and scroll down to device management and trust the new certificate for unc0ver.  Now unc0ver should open and you're in business.

**Comment by Hamlock-Maneuver** [comment]
I explained this to the creator of the Altstore, Not knowing who he was.   He was not very happy, to say the least.

**Comment by Hamlock-Maneuver** [comment]
BTW is case you didn't see it.  The link jbmagination posted should work if you don't want to setup the ISS manager.

**Comment by BotClancy** [comment]
@Hamlock-Maneuver Thanks I’ll try this when I get home!

**Comment by Hamlock-Maneuver** [comment]
I just tested this to make sure it still does work. You good to go.  Also I forgot to mention.  ISS manager is built into windows.  So you don't need to download it.

**Comment by BotClancy** [comment]
@Hamlock-Maneuver @jbmagination Thanks for the help I’m back to how it was but I could t figure out the ISS but luckily the uncover option was set to 3.8.0 already!

**Comment by BotClancy** [comment]
This uncover should never revoke correct?

**Comment by suprstarrd** [comment]
As long as your computer is active at least once per week, yes. See https://altstore.io/faq/ for more understanding on how AltServer works

**Comment by BotClancy** [comment]
Thanks!

**Comment by Hamlock-Maneuver** [comment]
What you want to do after recovering to this point, is to use a tweak called reprovision.  Its basically a tweak solely designed to install .IPA files and add certificates to them. Along side of Filza (another tweak EVERYONE should have) You can download any IPA file directly onto your phone. by using these tweaks together. you can install, and maintain certificates indefinitely.  This is only meant to be used in a jailbroken state.  

Anyway.  I'm glad you got it working.  If you need any more help, just ask.

**Comment by Hamlock-Maneuver** [comment]
As an example.  My mother is approaching 70 years old. She doesn't check or probably even know about the certificate thing.  Her Iphone Xr has been jailbroken for quiet awhile and her certificates still haven't expired.  Reprovision try's to auto renew them every few days, and it appears to be working for her.
