### ISSUE TITLE
[Help] Error message with Unc0ver 4.x.x only

### ISSUE THREAD

**Issue by SwagJesus** [pwn20wndstuff/Undecimus#1820]
Whenever I try to jailbreak i get this error. Airplane mode on or off; same results.
 - iOS Version: 12.4.1
 - iOS Device: Xs max
 - unc0ver Version: 4.2.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x ] this issue is present on the latest version of unc0ver

![pjygfw3cfsj41](https://user-images.githubusercontent.com/25094919/75600813-05eeb600-5a82-11ea-81c9-f69f6f4d9b5c.jpg)

**Comment by Hamlock-Maneuver** [comment]
I'm not positive.  But I'm pretty sure it doesn't work with this version of IOS. Why didn't you update to 13.3 like everyone said to?

**Comment by SwagJesus** [comment]
> I'm not positive. But I'm pretty sure it doesn't work with this version of IOS. Why didn't you update to 13.3 like everyone said to?

Because I'm on Unc0ver 3.8.0 & it working fine.
![D00C4DCA-3C08-4C84-9D04-A8BB4CBB4946](https://user-images.githubusercontent.com/25094919/76122843-198ba680-5fc5-11ea-8233-a0176aa2214b.png)

**Comment by Hamlock-Maneuver** [comment]
Then why would you post trying to use 4.2.1 and ask why its not working? 
Please mark your post as resolved.  Don't waste our time here please. Thank you.

**Comment by SwagJesus** [comment]
Because Unc0ver 4.0.3 is not working for several others who have a iPhone X Max or XR. If you don’t have a resolution, please stop replying. Thank you.

**Comment by SwagJesus** [comment]
Because Unc0ver 4.0.3 is not working for several others who have a iPhone X Max or XR. If you don’t have a solution, please stop replying. Thank you.

**Comment by Hamlock-Maneuver** [comment]
Well What you just said is all fine and dandy, except that it has nothing to do with our conversation.   Look at the picture you posted at the top.  You are using 4.2.1   Now look at the picture at the bottom.  You are using 3.8.0.   Nobody said anything about 4.0.3.  Get your shit together and then come at us with a legit question.  Otherwise.  Stop posting here.

**Comment by suprstarrd** [comment]
Bruh, it is a legitimate problem for someone using 4.2.1, and 4.0.3 shouldn't be any different. After all, he said 4.x.x. Get out of here if you're not looking to help the people who have legitimate problems.

If I was using an outdated app, I'd likely want to update the app. Why wouldn't I upgrade unc0ver to 4.2.1 if I use 3.8.0? So what?

Pwn's taking his time and I respect that. I thank him for that and he's testing it greatly. That's awesome. However, you're really not showing the best of yourself here right now.

It is a problem, and it can be fixed if Pwn recognizes it.

If people aren't able to jailbreak as promised then people will complain and report the bug. It _does_ have something do with the conversation, he wants it fixed.

You literally joined almost a week ago, and I presume you're very inexperienced in having actual conversations online without having a freakout considering the way you're acting (and have been on other issues), so as you've said to him: get yourself together, then come at us with a legitimate answer. Otherwise, stop posting here.

**Comment by Hamlock-Maneuver** [comment]
Jbmagination.  Stay on topic. Or don't post your nonsense at all. Read the post and what actually happened. I told him it doesn't work with 4.2.1.  he agreed and said it works on 3.8.0. Stop wasting peoples time telling everyone to retore rootfs. If you can't help.  Then don't try. If you got beef with me.  Then private message me.  Don't post your bullshit here.

**Comment by suprstarrd** [comment]
@Hamlock-Maneuver I tell people to restore RootFS to rule it out. It solved most of my problems so it's the first thing I tell people to do so that we can rule it out in the end.

I was a bit angry yesterday so I apologize for my ignorance at the end, but most of what I said I still stand by. I'm trying to help people out just as you are. I presume that he just wants it fixed is all, since it worked before.
