### ISSUE TITLE
(iPhone 6s iOS 12.1.1) /usr/libexec/cydia/cydo returned an error code (255)

### ISSUE THREAD

**Issue by qwertyuiop1011** [pwn20wndstuff/Undecimus#1828]
**Describe the bug**
None of my "tweaks" are working and I keep receiving /usr/libexec/cydia/cydo returned an error code (255) whenever I try to update or install anything. Not sure if this is related to my Touch ID not working when I replaced my iPhone's LCD screen or the latest version of Unc0ver.
**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: iPhone 6s
 - unc0ver Version: 4.0.3

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
/usr/libexec/cydia/cydo returned an error code (255)

**Comment by suprstarrd** [comment]
Here are some tips to go through:

a) Try re-installing Cydia and jailbreaking again.
b) Re-install unc0ver.
b) If this doesn't work, restore RootFS (if you have any tweaks installed this will automatically remove them!)
c) If restoring RootFS doesn't work, reinstall unc0ver again.

You're getting the error code because there is an error with Cydo, likely something missing.
