### ISSUE TITLE
Exploit failed on iPhone 8 using unc0ver v4.3.1

### ISSUE THREAD

**Issue by Brobbo41** [pwn20wndstuff/Undecimus#1844]
A pop-up occurs on Unc0ver. I am unable to jailbreak. The message I receive says...

Notice
Unable to exploit kernel. This is not an error. Reboot and try again.

**To Reproduce**
Not able to reproduce

**Screenshots**

![IMG_3665](https://user-images.githubusercontent.com/61969096/76204100-b43ced00-6232-11ea-8e1a-2116f9483b49.PNG)

**Device (please complete the following information):**
 - iOS Version: 13.3
 - iOS Device: iPhone 10,1
 - unc0ver Version: 4.3.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [X] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

"Unable to exploit kernel. This is not an error. Reboot and try again."

**Comment by Hamlock-Maneuver** [comment]
How many times have you tried?  Sometimes it can take up to 5 times.  When it says reboot.  Do a hard reboot.  Volume up, volume down, hold lock button untill screen goes black.

**Comment by Brobbo41** [comment]
> How many times have you tried? Sometimes it can take up to 5 times. When it says reboot. Do a hard reboot. Volume up, volume down, hold lock button untill screen goes black.

I have tries over 10 times rebooting each time. Doing a hard reboot does not solve the issue.

**Comment by Hamlock-Maneuver** [comment]
Try an older version of unc0ver.   Also, you do have the option of using checkra1n.

**Comment by Cryptiiiic** [comment]
@BaileyRob41 go into dfu mode, come out of dfu mode, then try jailbreaking again.

**Comment by varohh** [comment]
@BaileyRob41 did you ever fix this?

**Comment by andre104623** [comment]
Why is it so hard to use checkm8 it’s the most sable best jailbreak there is and you know the best part you can update to the latest iOS and still jailbreak and don’t give me that “I don’t have a Mac” use Linux it takes 4 seconds to jailbreak once u use checkm8 over uncover you will never go back

**Comment by darkvvibes** [comment]
I had the same problem as you. I would get the same message and I'm running IOS 13.3 iPhone XS. The way it started for me was my phone was already jailbroken a few days ago but yesterday I tried installing a tweak that made my phone freeze and then restart and I ended up losing my jailbreak from unc0ver. Cydia and ReProvision were still on my phone but I couldn't open them because I wasn't jailbroken because I lost my jailbreak. I tried everything and nothing worked. I tried jailbreaking my phone like 5 times before that error message started popping up and the jailbreak process would finish and my phone would restart but it took a very long time for it to restart my phone and when my phone finally turned on it still wasn't jailbroken and then after that the error message started popping up. Somehow along the way I was able to delete the unc0ver profile I don't remember how but then I ended up reinstalling unc0ver through AltStore with the ipa.

After reinstalling unc0ver these are the steps that I did that ended up fixing and getting my phone to jailbreak.

1. Make sure Siri is turned off and Airplane mode is turned on.

2. Soft reboot your phone by quickly pressing and releasing the volume up button and quickly pressing and releasing the volume down button and then press and hold the side button until your phone reboots and shows the apple logo.

3. After your phone is turned on make sure that airplane mode is still on and make sure your wifi is disabled and off.

4. Go into the unc0ver app and try jailbreaking your phone while airplane mode is turned on and wifi is off. (For me the error message didn't pop up because I think doing step 2 made it stop). For me it didn't jailbreak my phone after it rebooted because I still couldn't open Cydia or ReProvision, but doing this step tricked the system into thinking I jailbroke my phone but it didn't work

5. Make sure Airplane mode is still on and wifi is off and go back into unc0ver and go into settings and turn on RestoreRootFS and restore the phone. The phone still thinks it was jailbroken from before so when restoring it, it got rid of Cydia and ReProvision.

6. After it restores, go back into unc0ver while airplane mode is on and wifi is turned off and make sure RestoreRootFS is disable in settings and try jailbreaking your phone. It should jailbreak, reboot and it should be jailbroken with Cydia installed :)

**Comment by etrombone** [comment]
Hey I did your method and I didn’t even have to do step 5. Thanks!

**Comment by Cryptiiiic** [comment]
@darkvvibes Airplane mode has absolutely nothing to do with anything...

**Comment by dontbanmeplz** [comment]
I just turned on clear cydia cache and turned off Siri and it worked

**Comment by oneduality** [comment]
I had this today and all I did was enable airplane mode.. worked right away when I did that.

**Comment by Keekay-OD** [comment]
DFU and Airplane mode worked!

**Comment by oneduality** [comment]
@OmarDTech  good to hear :)
