### ISSUE TITLE
11.3.1 iPhone X Stuck on 24/40

### ISSUE THREAD

**Issue by dalvo2** [pwn20wndstuff/Undecimus#194]
Running newest Unc0ver. 2.1.0. I tried it also using 2.0.2, kept getting exploit errors.

The error now, is when run, the app freezes / "hangs" on 24/40. Tried it half a dozen times, restarting before each run.

I have ran 'reinstall cydia' 'tweeks off' 'reinstall ssh' and a number of other ways, each had the same issue.

**Comment by jvreeken** [comment]
I can’t seem to get past 1/40
Using iPhone X on 11.3.1
I’ve only ever been able to jailbreak using the multi path exploit by using a signing service...

Want to try to use my own but can only use the empty list exploit.

I’ve tried everything I can think of...

Guess I’ll just wait until signing services update.

**Comment by digitalhouse** [comment]
> I can’t seem to get past 1/40
> Using iPhone X on 11.3.1
> I’ve only ever been able to jailbreak using the multi path exploit by using a signing service...
> 
> Want to try to use my own but can only use the empty list exploit.
> 
> I’ve tried everything I can think of...
> 
> Guess I’ll just wait until signing services update.
> 
> Every time I try, my phone just immediately restarts...
> 
> Installed 2.1.0 via tweakbox and it jailbroke on the first try.

i have same issue(1/40 and reboot) i try 10+ times but when i just keep try it it just work

**Comment by Cryptiiiic** [comment]
@jvreeken @digitalhouse failing at 1/? has nothing to do with unc0ver. That means the exploit failed.
@dalvo2 please post unc0ver diagnostics.

**Comment by CoolPersonMaam** [comment]
@digitalhouse @jvreeken exploit aidnt reliable enough. You have to do it properly. 1. delete all pending updatrs you have and turn off find my iphone and passcode and get out of low battery mode. Now you want to restart youre device then opening it. Then, wait at the unc0ver screen for 30-45 secs then hit jailbreak sometime u have to lock the device depends and turn on airplane mode if its not working or turning off siri too. the exploits best reliable that way. Lastly, if u want the MP version please visit jailbreak.fun this is the site /r/jailbreak approves too if u want to sign the app your self for MP if not do the things i did tell u to on the top just keep trying its a 2 time try once u try it tho at 24/? it will ask you for a snapshot then u hit ok and keep trying. Its that your not doing it correctly its because its not like electea so u have to do it manually

**Comment by Cryptiiiic** [comment]
@dalvo2 does this still occur
