### ISSUE TITLE
Apps crash on unc0ver, but work perfectly in checkra1n

### ISSUE THREAD

**Issue by SarKaa** [pwn20wndstuff/Undecimus#2009]
**Describe the bug**
Certain apps freeze and crash on unc0ver, and work perfectly on checkra1n

**To Reproduce**
1. Jailbreak with checkra1n
2. Jailbreak with unc0ver after installing with altstore
3. Jailbreaking with unc0ver after rebooting
4. Apps like chrome, mail, WhatsApp etc don’t open

**Device (please complete the following information):**
 - iOS Version: 13.4.1
 - iOS Device: iPhone 7 Plus
 - unc0ver Version: 5.0.1

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver
^^^ haven’t tried any of the other options, cos I am fine with using checkra1n

**Comment by aacmartin** [comment]
11 Pro Max.  Everything you listed above working 110% perfectly, zero issues.
unc0ver 5.0.1
iOS 13.5

**Comment by SarKaa** [comment]
> 11 Pro Max. Everything you listed above working 110% perfectly, zero issues.
> unc0ver 5.0.1
> iOS 13.5

Yeah I know that’s strange, because no one else has gotten this error before

**Comment by aacmartin** [comment]
If you want a signed executable that just does a NSLog with a delay to observe (not that you can't do this yourself, all 3 lines of code), I can give one to you.
What's even more interesting (Okay, I have an agent that I developed a while back to capture the lock-screen passcode), is that it runs VASTLY slower (around 10x) when the lock-screen is active versus when its not active.(Not to mention they changed in 13.5 how the screen buffer/capture works [or rather, the data that comes back], but thats a completely different discussion).
Anyway..since its trivial, here's the code (Add the #includes as needed):
int main(int argc, char **argv)
{
#pragma unused(argc)
#pragma unused(argv)
    printf("Begin %s %s\n", __TIME__, __DATE__); //Or use NSLog(@"blah");    [NSThread sleepForTimeInterval: .25];
    return (0);}

this is the plist I use:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>application-identifier</key>
        <string>com.zzz.my-idevice-tools</string>
        <key>com.apple.backboard.client</key>
        <true/>
        <key>com.apple.wifi.manager-access</key>
        <true/>
        <key>get-task-allow</key>
        <true/>
        <key>keychain-access-groups</key>
        <array>
            <string>apple</string>
        </array>
        <key>platform-application</key>
        <true/>
        <key>com.apple.private.allow-explicit-graphics-priority</key>
        <true/>
        <key>com.apple.QuartzCore.global-capture</key>
        <true/>
    </dict>
</plist>
and to sign:codesign --force --sign "iPhone Developer: [REDACTED]" --entitlements ent.plist $(BIN_NAME)






    On Wednesday, May 27, 2020, 10:34:06 AM CDT, SarKaa <notifications@github.com> wrote:  
 
 



11 Pro Max. Everything you listed above working 110% perfectly, zero issues.
unc0ver 5.0.1
iOS 13.5


Yeah I know that’s strange, because no one else has gotten this error before

**Comment by SarKaa** [comment]
I just rejailbroke with unc0ver after switching back to checkra1n, and it worked
