### ISSUE TITLE
Will Cycript be supported on unc0ver?

### ISSUE THREAD

**Issue by liuxuan30** [pwn20wndstuff/Undecimus#205]
Hi there, I'm not sure if this is the right place to ask, but will Cycript be supported on unc0ver? Since substrate is already supporting iOS11.

**Comment by sbingner** [comment]
It already works you just need to install it.  Hopefully saurik will host it somewhere that it can be installed from soon.  Probably wherever he puts Substrate once he’s satisfied it is no longer beta (which it may be now)

Sam

On Jan 1, 2019, at 4:15 PM, Xuan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there, I'm not sure if this is the right place to ask, but will Cycript be supported on unc0ver? Since substrate is already supporting iOS11.

**Comment by liuxuan30** [comment]
Hi @sbingner thanks for reply. I tried to add http://apt.saurik.com, but unc0ver 2.1 cannot add it. Can you tell me what repo can have it? or we have to wait until substrate is in production?

btw, I'm asking this is because debugserver is not working. I signed it with enough entitlements for iOS 11 debugserver, but running ` /var/root/debugserver` just said `cannot execute binary file: Operation not permitted`
the ent file I used:
[serv-ent.txt](https://github.com/pwn20wndstuff/Undecimus/files/2720004/serv-ent.txt)

**Comment by sbingner** [comment]
No repo just download and install the deb file.  You may need to add platform-application entitlement

Sam

On Jan 1, 2019, at 8:11 PM, Xuan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @sbingner<https://github.com/sbingner> thanks for reply. I tried to add http://apt.saurik.com, but unc0ver 2.1 cannot add it. Can you tell me what repo can have it? or we have to wait until substrate is in production?

btw, I'm asking this is because debugserver is not working. I signed it with enough entitlements for iOS 11 debugserver, but running /var/root/debugserver just said cannot execute binary file: Operation not permitted
the ent file I used:
serv-ent.txt<https://github.com/pwn20wndstuff/Undecimus/files/2720004/serv-ent.txt>

**Comment by eziochiu** [comment]
I found a cycript from http://jakeashacks.ga/cydia/, you can try it before saurik release his repo. it base on new cydia substrate and it can fully work on iOS 11 and arm64 device

**Comment by liuxuan30** [comment]
yes, adding ents will be able to use cycript. cheers

**Comment by BigFaceCat2017** [comment]
> yes, adding ents will be able to use cycript. cheers

重签了cycript就可以再ios11用cycript了？
