### ISSUE TITLE
An error occurred while obtaining entitlements. (Not a signing issue)

### ISSUE THREAD

**Issue by Jack06WS** [pwn20wndstuff/Undecimus#2063]
**Describe the bug**
Error "An error occurred while obtaining entitlements" pops up after pressing the Jailbreak Button.

**To Reproduce**
1. Go to the unc0ver application
2. Click on "Jailbreak"
3. See error

**Screenshots**
https://imgur.com/a/buzoNEs This is the error.

**Device (please complete the following information):**
 - iOS Version: 13.5
 - iOS Device: iPhone XS (11,2)
 - unc0ver Version: 5.20

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
[*] unc0ver is not for sale
[*] If you purchased unc0ver, please report the seller
[*] Get unc0ver for free at https://unc0ver.dev
[*] Configured to share anonymous OS crash logs
[*] Machine Name: iPhone11,2
[*] Model Name: D321AP
[*] Kernel Version: Darwin Kernel Version 19.5.0: Tue Apr 28 22:24:50 PDT 2020; root:xnu-6153.122.1~1/RELEASE_ARM64_T8020
[*] Kernel Page Size: 0x4000
[*] System Version: iOS 13.5 (Stable) (Build: 17F75)
[*] Stage (1): Ensuring resources
[+] Ensured resources
[*] Stage (2): Exploiting kernel
[haxx] We in quarantine but still out here!
[+] Exploited kernel
[*] Stage (3): Initializing
[*] Stage (4): Finding kernel slide
[+] Found kernel slide: 0x9164000
[*] Stage (5): Finding kernel offsets
[+] Found kernel offsets
[*] Stage (6): Finding data structures
[+] Found data structures
[*] Stage (7): Obtaining root privileges
[+] Obtained root privileges
[*] Stage (8): Disabling sandbox
[+] Disabled sandbox
[*] Stage (9): Updating host port
[+] Updated host port
[*] Stage (10): Enabling dynamic codesign
[+] Enabled dynamic codesigning
[*] Stage (12): Saving kernel task port
[+] Saved kernel task port
[*] Stage (13): Saving kernel task info
[+] Saved kernel task info
[*] Stage (14): Disabling codesigning
[+] Disabled codesigning
[*] Stage (15): Obtaining entitlements

**Notes**
- These errors still happen after erasing my iPhone through settings. This error also accures when using Cydia Impactor and AltStore so I don't think it's a signing issue like the FAQ's are saying. I've spent lots of time googling this issue and I can't find any fixes, so I've come here.

**_Jack_**

**Comment by Hamlock-maneuverr** [comment]
Try using a different apple id

**Comment by Jack06WS** [comment]
> Try using a different apple id

That doesn't seem to fix any issues for me. The same error occurs when using different Apple ID's and different signing tools.

**Comment by samdh90** [comment]
Have you tried via WiFi and cellular? Do you any sort of content filtering or “VPN” apps? I wonder if the server is being blocked by either a firewall, or a content filtering app.

**Comment by Mister-C89** [comment]
Today Cydia suddenly fucked up my iPhone 11 iOS 13.5. Have been running flawlessly since the release of Unc0ver 5 for all devices.

1) Opened Cydia and it told me there were 2 updates
2) and update for "A-Bypass" and "Boxy 4"
3) Clicked upgrade and I got this error in Cydia: "Half-Installed Package" and could click "Ignore" or "Forcibly clear". The ignore didn't help and could not upgrade the mentioned tweaks. So I tried to forcibly clear and Cydia removed a lot of standard tweaks and my own installed tweaks, and came with even more errors now: "subprocess was killed by signal (Abort trap: 6).
4) Restarted springboard and opened Cydia again:
5) Now GPG errors with "failed to fetch" etc. Then Cydia wanted to install "AppList, Base Structure, Core Utilities, Essentail, Link Identify Editor, New Curses, Profile Directory and readline" again, and still upgrade "A-Bypass" and "Boxy 4 (iOS 13).
6) Clicked "Confirm" and restarted springboard and opened Cydia again because it gave GPG errors gain, and now Cydia said "3 Half-Installed Packages" and then "only" "AppList, Base Structure. Essential, Link Identify Editor and Profile Directory" and upgrade "A-Bypass and Boxy 4 (iO 13)" was showing up. I ignored it, and my Phone began to fuck up. I tried restarting the phone an jaibreak again. But not Unc0ver and AltStore wouldn't open (They were confirmed in the settings!) (Was using the 1.4.3a of AltStore with the Altstore Daemon etc, which was working perfectly normally, also after rebooting. But I had to remove them, and install AltStore again from PC, trust developer, and istall Unc0ver again through AltStore. But now Unc0ver wouldn't jailbreak. And the phone was downloading iOS 13.5.1 in the background OTA. Unc0ver stopped at 15/31 and said "An error occurred while obtaining entitlements" ... I have tried several hard reboots, re-installd Altstore and differents versions of Unc0ver again, ticked different settings in Unc0ver - all without any difference. 

Now I can't turn on Airplane mode, cellular doesn't work (Only wifi works), can't open Telephone app, Message app, Instagram app, and can't see storage to delete the downloaded update file for ios 13.5.1. WHAT THA FUCK! How the FUCK can Cydia fuck up the entire phone just by removing some tweaks? And make it impossile to even simply jailbreak again.... Can't even RestoreFS. Wuhuuu. Now I'm forced to restore and fucking update to 13.5.1. Just as Apple wished. They probably hacked my phone and began to fuck it up and block Unc0ver jailbreaking process and mes up the rest of the phone.

**Comment by Hamlock-maneuverr** [comment]
A-Bypass will cause this.  You need to restore rootfs and start over. Go to settings, general, reset, reset all setting.

**Comment by Mister-C89** [comment]
That’s too late. I couldn’t restore rootfs. Tried everything possible, but Unc0ver didn’t jailbreak.

How would that tweak cause Cydia to go bananas? 

I removed it from another of my devices though, without any problems. But on my phone I tried upgrading at first. Maybe that’s why it fucked up Cydia totally? But Cydia is also quite stupid coded, if there’s a bug in ONE tweak and it wants to remove almost every standard tweak which has absolutely nothing to do with A-bypass.. I don’t get it why Unc0ver got butthurt though...

**Comment by mho686** [comment]
Exactly, I encountered the same problem in my phone .. and the same things that I mentioned (flight mode, cellular data, most applications) do not work at all ... in case you got a solution to this problem help me 🙏🏻

**Comment by mho686** [comment]
@Mister-C89 if u do solve the problem with Erasing all content and setting ..text me 🙏🏻

**Comment by Mister-C89** [comment]
> @Mister-C89 if u do solve the problem with Erasing all content and setting ..text me 🙏🏻

I did solve it. I restored the fucking phone and was forced to upgrade to 13.5.1. So the errors are gone - but so is the option to JB ofc🙄
That was the only solution.

Thanks Apple. Thanks Cydia. Thanks Unc0ver. You “guys” should consider team up, because you could overtake the world........

But by the way. My phone is quite faster now though, so it’s just about to be worth it.

**Comment by mho686** [comment]
So happy for u .. i hope u help me by stips 😭 
If u contact me on direct

**Comment by madistani** [comment]
The same happened to me on my iphone Xs 13.5  jailbroken with unc0ver 5.2.0, it all started when cydia told me i had one upgrade but after installing that i got an error saying “half-installed package” and gave me two options 
A. Ignore 
B. Forcibly clear (unsafe).
I tapped on ignore first then I carried on to install a new tweak glitchpods13 however it failed with some kind of trap 6 error and again that half installed package error popped-up and this time i tapped on the second option, the unsafe one. 
My device re-springed and this is the situation i am in right now:
1. All my tweaks are disabled/gone
2. My JB apps like filza and itorrent are working fine
3. When i try to re-jailbreak with the unc0ver app it gives me The same error as above the entitlement one.

Im confused and right now,  im gonna use my phone as it is, im not gonna open cydia again although its showing me three new upgrades, however everything else is working fine.

After going through this thread i know im not totally fucked, can someone help me out here?

Anyways hoping for a solution from the devs. 
Peace ✌🏼

**Comment by Mister-C89** [comment]
It’s just so nice. Wasted money purchasing paid tweaks. Goodbye JB. Fucking sad. And no responsible developer nor hacker responds. They just don’t care do they?

**Comment by mho686** [comment]
Hi mister ,, do u backup data by phone Icloud or Pc !!

**Comment by Mister-C89** [comment]
Both. But iCloud works just fine.

I jused the software called 3U to do the restore. It’s a lot faster than iTunes!!

https://www.3u.com

**Comment by mho686** [comment]
Very nice ,, I already do Backup By phone iCloud,, So if i do Erase All content from phone settings 

Are all thing will be back normal!!

**Comment by zyi840449** [comment]
Hi guys. I encountered the exact same problem.
I tried Restore RootFS, but it didn't work, it gives me The same error as above the entitlement one.
So I stopped at 15/31 and couldn't start Restore RootFS.

I tried to use the reset function on the device, but after a successful restore, I still can’t turn on the airplane mode and still no cellular.

By the way, in this state, connecting the software 3U mentioned by others, will show that my device is jailbroken!
Does anyone have any suggestions on what to do?

**Comment by mho686** [comment]
Hi zyi ,

Yes my dear I already restore my phone by phone settings but no any solve for airplane mode and cellular 

So i do restore it by itunes i lost JB for 13.5 because already updated to 13.5.1 

This is one & only solve 😭

**Comment by mho686** [comment]
Hi zyi ,

Yes my dear I already restore my phone by phone settings but no any solve for airplane mode and cellular 

So i do restore it by itunes i lost JB for 13.5 because already updated to 13.5.1 

This is one & only solve 😭

**Comment by Mister-C89** [comment]
Sadly no. I can't seem to figure out what the problem exact is, other than Apple probably somehow managed to get into the filesystem and manipulate and block Unc0ver from doing it's thing and mess up the entire system. (Blocking cellular and flightmode, WTF. Hahahahaha. So you are FORCED to restore the phone and update to 13.5.1 and lose jailbreak). 

I'm now on my like 4th day with stock iPhone 11 iOS 13.5.1.  I have 2 other phones in the house (iPhone 7 and another iPhone 11), also jailbroken with Unc0ver and on iOS 13.5. They are still running without any issues and renewing Altstore and Unc0ver through Altstore daemon locally perfectly. Haven't tried restarting the phones yet, and hope I'm not forced to do that and find out if Unc0ver will jailbreak again or not.

It's such a shame. Totally pathetic.

**Comment by Mister-C89** [comment]
And apparently pwn20wnd doesn't care for a quick fix. He probably got paid to fuck it up, by Apple or so.

**Comment by mho686** [comment]
Hi mister, good evening,, do u install altsotre by phone with 3 more tweaks!!

**Comment by Mister-C89** [comment]
> 
> 
> Hi mister, good evening,, do u install altsotre by phone with 3 more tweaks!!

What do you mean?

**Comment by zyi840449** [comment]
Do you use CyDown?
I wonder if the system is messed up due to the "special tweak installation method" of this tweak?

**Comment by mho686** [comment]
I mean do u install altstore from cydia from the source https://pwnders.github.io/repo/ and add uncover with 7 day’s certificates!!

**Comment by zyi840449** [comment]
> I mean do u install altstore from cydia from the source https://pwnders.github.io/repo/ and add uncover with 7 day’s certificates!!

yes,i have

**Comment by Mister-C89** [comment]
Yes

https://youtu.be/FD65POANGOo

**Comment by mho686** [comment]
#Dear zyi I don’t use cydown but after i restore my phone from phone setting all apps are removed except ReProvision I don’t know how i delete it bcz at same time I didn’t find anyway to Jailbreaking my phone again so i take the next stips and restore it by ITunes 😭😭

**Comment by zyi840449** [comment]
What about kernbypass?
Or other programs that prevent jailbreak detection, have you installed them?

I want to sort out common ground to prevent others from encountering the same problem

**Comment by Mister-C89** [comment]
Yep.. Kernbypass 0.0,3 as a daemon so after restarting it would run the code automatically. Never had any problem with that and jailbreak again after restarting etc.

**Comment by madistani** [comment]
Great news the new update 5.2.1 of uncover resolved my issues.
Fully jailbroken again.
Thanks for the support dev ❤️

**Comment by Mister-C89** [comment]
> Great news the new update 5.2.1 of uncover resolved my issues.
> 
> Fully jailbroken again.
> 
> Thanks for the support dev ❤️

Congratulations that it solved your issue. And that your phone wasn’t fucked up as a lot of others like mine, who was forced to restore and update to 13.5.1 and lose JB for years now. So pathetic that it’s not possible to restore with blobs. I managed to save them anyway, before the JB fucked it all up. But it doesn’t look like a working method is coming. Maybe when iOS 20 is released. Wohoooo. 

Have a great life everybody 👏

**Comment by Jack06WS** [comment]
I never actually managed to get mine fixed. Everybody at the unc0ver team has refused to help me with the issue. I ended up updating to iOS 14 BETA which is actually much more stable than iOS 13.5 with unc0ver. It must be such a hard issue to fix that the unc0ver team doesn't think it's worth fixing for the 5 people that will get the issue. I'm closing this issue for now, It's up to the developers to do what they want now. I don't really care anymore.

**### CLOSED**

**Comment by Jack06WS** [comment]
I never actually managed to get mine fixed. Everybody at the unc0ver team has refused to help me with the issue. I ended up updating to iOS 14 BETA which is actually much more stable than iOS 13.5 with unc0ver. It must be such a hard issue to fix that the unc0ver team doesn't think it's worth fixing for the 5 people that will get the issue. I'm closing this issue for now, It's up to the developers to do what they want. I don't really care anymore.

**CLOSED**
