### ISSUE TITLE
APT not working

### ISSUE THREAD

**Issue by J0113** [pwn20wndstuff/Undecimus#217]
Hi everyone,

because of some weird reason my APT is not working. I've ssh'ed into my iPhone succesfully but I am unable to use APT. Running `apt` will work but `apt list` fails. apt-cache and apt-get also fail. I have tried reinstalling all APT packages and installing APT Command Line, nothing is working. dpkg is working tho.

```
iPhone-van-Jolle:~ root# apt
apt 1.4.8 (iphoneos-arm)
Usage: apt [options] command

apt is a commandline package manager and provides commands for
searching and managing as well as querying information about packages.
It provides the same functionality as the specialized APT tools,
like apt-get and apt-cache, but enables options more suitable for
interactive use by default.

Most used commands:
  list - list packages based on package names
  search - search in package descriptions
  show - show package details
  install - install packages
  remove - remove packages
  autoremove - Remove automatically all unused packages
  update - update list of available packages
  upgrade - upgrade the system by installing/upgrading packages
  full-upgrade - upgrade the system by removing/installing/upgrading packages
  edit-sources - edit the source information file

See apt(8) for more information about the available commands.
Configuration options and syntax is detailed in apt.conf(5).
Information about how to configure sources can be found in sources.list(5).
Package and version choices can be expressed via apt_preferences(5).
Security details are available in apt-secure(8).
                                        This APT has Super Cow Powers.
iPhone-van-Jolle:~ root# apt list
Segmentation fault: 11
iPhone-van-Jolle:~ root# apt search .
Segmentation fault: 11
```

**Comment by J0113** [comment]
Okay, Restoring the RootFS seems to fix the issue!

I think updating to unc0ver v2 broke APT.

**Comment by J0113** [comment]
Okay, it broke again. I was just using APT, everything was working: `apt-get update` & `apt-cache search .` ect. I was even able to use `apt-get download [package]`. And than it stopped working returning the `Segmentation fault: 11` (logged in as root, whatever apt command I use). 

There is one topic about this issue (but has no answer): 
https://www.reddit.com/r/jailbreak/comments/6mh5j9/questionanyone_know_whats_going_on_segmentation/ 

`ps -e | grep -e apt -e adept -e dpkg | grep -v grep` does not return anything (no apt processes are running).

**Comment by J0113** [comment]
I have tried both as su and user. I have tried rebooting. I have tried aptitude.

**Comment by J0113** [comment]
Crash log: 
https://pastebin.com/raw/9LWs57AA

Installed packages:
https://pastebin.com/raw/WghP9Akf

**Comment by resistor4u** [comment]
@Cryptiiiic @J0113 
I've had apt-related issues since late November on my iphone 6s 11.3.1. I thought old or conflicting libs were lingering about, despite having done Rollectra. Using dpkg, I systematically went through removing packages and finally rm’ed Cydia.app and some items in /jb to ensure Undecimus would reinstall Cydia, etc. etc. Starting fresh again, `apt-get update` returns this:
```
W: Error occurred while processing
org.thebigboss.loadingbartshirtbootlogo (NewVersion1)
W: Problem with MergeList
/var/lib/apt/lists/apt.thebigboss.org_repofiles_cydia_dists_stable_main_binary-iphoneos-arm_Packages
...
W: Ran out of allocation pools
W: Problem with SelectReleaseFile
/var/lib/apt/lists/creaturesurvive.github.io_._Release
W: Ran out of allocation pools
W: Problem with SelectFile /Library/dpkg/status
```
Then I tried `apt update`, which gave a little output before failing with `Segmentation fault 11.. 87%`. Each time I try any `apt-get` commands, they now also fail with seg fault 11.

Here are links to three crash reports from mid December:
[apt-cache crashlog](https://gist.github.com/resistor4u/f0176c46fe60b4d17365ffdf5d897c6d)
[apt-get crashlog](https://gist.github.com/resistor4u/2eb9158ac848e7f6ebd5f55b90fcab1a)
[apt-get crashlog 2](
https://gist.github.com/resistor4u/7f15df80882c8f4551f5578fe0802302)

I seem to remember that once upon a time, the allocation pools error was indicative of too many sources. Is this still the case?

**Comment by sbingner** [comment]
@resistor4u there is a bug in command-line apt-get that causes it to segfault if you have too many packages that I haven’t tracked down yet.  Remove a few repos or use cydia.
