### ISSUE TITLE
VEENCY

### ISSUE THREAD

**Issue by PapiCurtis** [pwn20wndstuff/Undecimus#259]
ability to. COPY & PASTE,  DRAG & DROP  would be even bicer than before

**Comment by bigrck64** [comment]
@PapiCurtis : Hello! did you manage to make veency work with Undecimus-v3.0.0-* ?
I tried Saurik's veency_0.9.3500_iphoneos-arm.deb with iOS 11.1.2 / 11.3.1, it installed correctly, I can connect to port 5900, but "left click" is not working on 11.1.2 and springboard is crashing on 11.3.1

**Comment by PapiCurtis** [comment]
wow,  i just saw this email on 03-29-2019 @ 02:10:52
can i reply to the email thread ??
thank you for writing
no, i still have my 11.3.1  in the drawer since i cannot use it without
VEENCY

i have not tried it
i dont know what "undercimus-v3.0.0     is ??

if you can further give me more details
you will be my HERO forever !!

**Comment by bigrck64** [comment]
I think that if you were creating one issue about new ability of veency for unc0ver, maybe it was because you were able to run it on iOS11 or 12 :)

- Undecimus-v3.0.0-b48.ipa is latest release of unc0ver for iOS 11 / 12
https://github.com/pwn20wndstuff/Undecimus/releases

- unc0ver is now using saurik's substrate, that why veency should be more compatible with it than substitute

- my test of veency_0.9.3500_iphoneos-arm.deb with Undecimus-v3.0.0-b48.ipa over iOS 11.1.2 and 11.3.1 show me that the service is starting, that I can connect to it and see the screen, but that I  can't send command (11.1.2 = no left clic / 11.3.1 = springboard crash)

so sorry, I'm still looking for a dev to help us recompiling [mouse support](https://www.reddit.com/r/jailbreakdevelopers/comments/b1ysyo/help_anyone_rebuild_mouse_support_successful_on/) and veency to make it work with unc0ver on iOS 11 and 12.

**Comment by PapiCurtis** [comment]
yea i did
then PWN said that soon(ish)
then someone closed the thread
tho still not solved

thank you for following up
IF you get it working please let me know
i have had a beautiful 11.3.1 thats been in the drawer

AND i am using my iphone5 9.0.2
VEENCY really is must must must have
for me. :(

every now AND then I spam on tweeter
see IF anyone picked it up

i hope you can get it to work

then tell me the step BY step
thank you
