### ISSUE TITLE
Unc0ver 2.2.2 Fatal error, failed to extract bootstrap

### ISSUE THREAD

**Issue by Wanqed** [pwn20wndstuff/Undecimus#290]
I decided to switch to Substrate as soon as v2.2.2 was released in hopes it’d get my tweaks to load, but with no luck I haven’t even gotten jailbroken once. Takes about 30 tries to even get to the error then reboot.  https://m.imgur.com/gallery/jsQ1Fcg

**Comment by Wanqed** [comment]
Error also says “install Deb (dpkg_deb.UTF8String, true)”

**Comment by Wanqed** [comment]
Ok well since the imgur won’t stay up here’s the whole error—— 

Error (Fatal)
     Errno:9
Test: installDeb(dpkg_deb.UTF8String, true)
Filename: JailbreakViewController.m
Line:1392
Function: Exploit
Description: Failed to extract bootstrap.

———End of error——


And if more info or anything else needed I will send diagnostics data

**Comment by sbingner** [comment]
I need the diagnostics or the last few messages in your log window.  If you switch to 3.x you should have an exploit that works every time (VS)

**Comment by Wanqed** [comment]
@sbingner I’ve switched to v3 but still same error where would u want me to send the diagnostics list?

**Comment by Wanqed** [comment]
I have this - https://imgur.com/gallery/RVMnogC - if you need diagnostics logs let me know

**Comment by sbingner** [comment]
Looks like there’s something wrong with your filesystem.  If you can upload your diagnostics plist it might tell me something

**Comment by Wanqed** [comment]
https://ufile.io/qza4d - should take u to the diagnostics plist, do u think the file system problem would have tied in with why my Substrate wouldn’t load any tweaks in the past? Because whenever I had tried to download substrate and remove substitute and I had even restored rootFS and then download substrate the first thing but no tweaks would load at all

**Comment by Wanqed** [comment]
Or maybe this will work, just realized that website has ads like crazy. 

Diagnostics.plist - https://drive.google.com/file/d/1T6asKVnjEZ_NHmUdsC-ip806rxkF6T6D/view?usp=drivesdk

**Comment by sbingner** [comment]
That diagnostics is empty.  You need to send one from after the error happens and before you delete the app or reinstall it

Sam

On Feb 2, 2019, at 2:34 PM, Wanqed <notifications@github.com<mailto:notifications@github.com>> wrote:


Or maybe this will work, just realized that website has ads like crazy.

Diagnostics.plist - https://drive.google.com/file/d/1T6asKVnjEZ_NHmUdsC-ip806rxkF6T6D/view?usp=drivesdk

**Comment by Wanqed** [comment]
@sbingner oh sorry, I ran the jailbreak again to get the error to pop up and this should have it in it now.

https://drive.google.com/file/d/10_WYbxTYHcrN83hNSM_nlyABnc5GOegH/view?usp=drivesdk

**Comment by sbingner** [comment]
That one looks the same - there should be a LOT more data (everything you see in the log window goes to a logfile that gets included)

Sam

On Feb 2, 2019, at 3:31 PM, Wanqed <notifications@github.com<mailto:notifications@github.com>> wrote:


@sbingner<https://github.com/sbingner> oh sorry, I ran the jailbreak again to get the error to pop up and this should have it in it now.

https://drive.google.com/file/d/10_WYbxTYHcrN83hNSM_nlyABnc5GOegH/view?usp=drivesdk

**Comment by Wanqed** [comment]
What am I doing wrong then? I ran the jailbreak, got the error code, clicked ok it exited and then I clicked share diagnostics log. Is there an email I could just email you it? I feel like apples “files” app is restrictng the file.

**Comment by sbingner** [comment]
That sounds right - I’ll test to make sure something didn’t mess up diags.  You installed directly from github with impactor right?

Sam

On Feb 2, 2019, at 3:47 PM, Wanqed <notifications@github.com<mailto:notifications@github.com>> wrote:


What am I doing wrong then? I ran the jailbreak, got the error code, clicked ok it exited and then I clicked share diagnostics log. Is there an email I could just email you it? I feel like apples “files” app is restrictng the file.

**Comment by Wanqed** [comment]
I did not, with the way things are for me rn I have no access to internet because cable company messed up my payments and stuff, I downloaded via jailbreaks.fun would it make a difference if I downloaded it from github or not? Or if I should try the v2.2.3 instead and see if it shows the full diagnostics log?

**Comment by sbingner** [comment]
You could try that.  it SHOULD not make a difference but I don’t know if they may have done anything to it.

Sam

On Feb 2, 2019, at 5:04 PM, Wanqed <notifications@github.com<mailto:notifications@github.com>> wrote:


I did not, with the way things are for me rn I have no access to internet because cable company messed up my payments and stuff, I downloaded via jailbreaks.fun would it make a difference if I downloaded it from github or not? Or if I should try the v2.2.3 instead and see if it shows the full diagnostics log?

**Comment by Wanqed** [comment]
@sbingner alright I finally got 2.2.3 to show the error after like 20 tries but. 

https://drive.google.com/file/d/1N9au1KCGkKtdWkO3WixU3rT0ZZIHltfR/view?usp=drivesdk

**Comment by Wanqed** [comment]
Ok so my diagnostics is completely empty all of the time, I screen-recorded the whole jailbreak process going on in the log window. Maybe these screenshots will tell u anything? Because that’s where the error starts to take place. 

https://imgur.com/a/tF1ZDzH

**Comment by Wanqed** [comment]
@sbingner Yes I have restored RootFS countless times, I’ve wiped my whole device and restored from backup (I don’t think setting up as new device would help would it?) it says something about “lzma is not by coolstar”? I think that’s something that’s making things messed up. I have had issues with substrate not loading any of my tweaks in past. Which is why I was upset when substitute support was removed with v2.2.0 and above. I think it’s substrate because right after it says “starting substrate” it gives the error after all the other log files also. Idk, I’ll get the b9 and upload diagnostics once it’s being signed by jailbreaks.fun

**Comment by sbingner** [comment]
It gives that error after substrate because substrate handles code signing bypass... and those are just the things that run afterwards.  That dpkg message isn’t an error, it’s just verifying that the dpkg installed is compatible with unc0ver.  The error is the “Bad executable (or shared library)”

Sam

On Feb 2, 2019, at 11:47 PM, Wanqed <notifications@github.com<mailto:notifications@github.com>> wrote:


@sbingner<https://github.com/sbingner> Yes I have restored RootFS countless times, I’ve wiped my whole device and restored from backup (I don’t think setting up as new device would help would it?) it says something about “lzma is not by coolstar”? I think that’s something that’s making things messed up. I have had issues with substrate not loading any of my tweaks in past. Which is why I was upset when substitute support was removed with v2.2.0 and above. I think it’s substrate because right after it says “starting substrate” it gives the error after all the other log files also. Idk, I’ll get the b9 and upload diagnostics once it’s being signed by jailbreaks.fun

**Comment by sbingner** [comment]
BTW impacting (as opposed to loading from a signing service) is fine now since the VS exploit doesn’t need a dev cert and is the most reliable

Sam

On Feb 2, 2019, at 11:47 PM, Wanqed <notifications@github.com<mailto:notifications@github.com>> wrote:


@sbingner<https://github.com/sbingner> Yes I have restored RootFS countless times, I’ve wiped my whole device and restored from backup (I don’t think setting up as new device would help would it?) it says something about “lzma is not by coolstar”? I think that’s something that’s making things messed up. I have had issues with substrate not loading any of my tweaks in past. Which is why I was upset when substitute support was removed with v2.2.0 and above. I think it’s substrate because right after it says “starting substrate” it gives the error after all the other log files also. Idk, I’ll get the b9 and upload diagnostics once it’s being signed by jailbreaks.fun

**Comment by Wanqed** [comment]
@sbingner ahhh ok and I would definitely use impactor to sign the apps but I have no internet as of right now. Trust me I really hate using signing services but it’s the only way to do things for me as of now.

**Comment by Wanqed** [comment]
@sbingner alright awesome you fixed it and it works for me now thank you.

https://drive.google.com/file/d/1OnRHRMJFldF_UvU05qDptojifUH4P75z/view?usp=drivesdk

**Comment by Harash23** [comment]
@sbingner when my iPhone is suppose to respring into jailbroken state it just loads forever and never goes into jailbroken then I have to restart my phone and then it takes more than 10 times just get a loop of respring on iOS 11.3.1 and I tried multiple verision of uncover

**Comment by sbingner** [comment]
That is not this issue.  Jailbreak with tweaks disabled and troubleshoot the broken tweak.  Simplest is removing them all then adding things in until you get that error again.

Sam

On Feb 3, 2019, at 1:11 PM, Harash23 <notifications@github.com<mailto:notifications@github.com>> wrote:


@sbingner<https://github.com/sbingner> when my iPhone is suppose to respring into jailbroken state it just loads forever and never goes into jailbroken then I have to restart my phone and then it takes more than 10 times just get a loop of respring on iOS 11.3.1 and I tried multiple verision of uncover

**Comment by sbingner** [comment]
I don’t know how to duplicate it but maybe I can work with you on teamviewer some time?  Can you join discord and ping me?

Sam

On Feb 3, 2019, at 1:30 PM, Wanqed <notifications@github.com<mailto:notifications@github.com>> wrote:


@sbingner<https://github.com/sbingner> let me know if there’s any fix for my problem, if not then I guess I’ll have to update somehow. Thanks in advance for being so active with my issue I really appreciate the fact that you guys help the community out a lot, it means very much.

**Comment by Wanqed** [comment]
@sbingner ok I’ve made a discord, it’s Wanqed#4640

**Comment by sbingner** [comment]
That is not the same issue.

Sam

On Feb 3, 2019, at 10:57 PM, Paz <notifications@github.com<mailto:notifications@github.com>> wrote:


had same issue on 3.0.0 beta 6, #293<https://github.com/pwn20wndstuff/Undecimus/issues/293>

**Comment by xPazz** [comment]
oh right i see now

**Comment by sbingner** [comment]
Duplicate of #214 where @Cryptiiiic managed to read the logfile better than I and identified the issue.
