### ISSUE TITLE
CodeInjection/WriteData on iOS 11.4.X

### ISSUE THREAD

**Issue by Archangel004** [pwn20wndstuff/Undecimus#360]
People have been reporting that any and all tweaks which use writeData (basically injecting modified hex during runtime) cause crashes on iOS 11.4.X.

I do not know if it is a substrate issue or a jailbreak issue. Apparently, Electra works with it, but due to obvious reasons, many people don't wish to use it.

**Comment by Cryptiiiic** [comment]
This has been publicly stated by sbingner(The person responsible for managing substrate) That the new substrate does not support memory patching in the constructor. The tweak developers have to update their tweaks to not do so. This won't be fixed because memory patching in the constructor is a bad idea to begin with. It is improper. Saurik is the deciding factor anyway since he makes substrate.

**Comment by Cryptiiiic** [comment]
@Archangel004

**Comment by Archangel004** [comment]
Is it possible to patch memory at all? Outside of debuggers that is.

**Comment by Cryptiiiic** [comment]
@Archangel004 read my message again. Also we can speak on discord.

**Comment by JohnCoates** [comment]
> developers have to update their tweaks to not do so. This won't be fixed because memory patching in the constructor is a bad idea to begin with. It is improper. Saurik is the deciding factor anyway since he makes substrate.

Why is memory patching in the constructor improper? I don't understand this viewpoint.

When is the soonest you can "properly" patch memory?
