### ISSUE TITLE
Cydia has a Network Error, Unable to Load (The internet connection seems to be offline)

### ISSUE THREAD

**Issue by VBQL** [pwn20wndstuff/Undecimus#499]
I have saved blobs for IOS 12.1, and upgraded from IOS 11.3.1 jailbroken with Unc0ver. Did the same on IOS 12.1. The jailbreak was instantly performed after setting up the iPhone. Succeeded on first attempt.

An issue popped up after jailbreaking, Cydia keeps telling me that there is no internet, even though there definitely is (tested with safari and downloading an app).

After some research it appears that since I have a Chinese iPhone (Model 6s), it can disable some apps from using the internet. However to fix this issue I need to delete a file, which would require me to have SSH access, yet SSH refused all my connection requests to the phone.

I have also found an ipa file called CydiaNetworkFix.ipa from xxtouch, which claimed to fix this issue. However, I did not have any luck with that either. (Bringing this up to let people know that I tried this solution already)

It seems like the only way now is to go into the filesystem and delete the file called "/var/preferences/com.apple.networkextension*", but apple file conduit is not installed by default so I cannot do that either.

I concluded maybe I wasn't paying attention while clicking through Cydia and accidentally disabled network access, so I futurerestored again to see if I was right. It turns out Cydia doesn't even ask for network access and just shows me the "connection offline" error.

Is there a script or anything I can do that forces the phone to let Cydia access to network?

Thanks :)

**Comment by VBQL** [comment]
Update, I realized you have to toggle (RE)Install OpenSSH, did that and got SSH access. Fixed the error. Sorry!

**Comment by krytrix** [comment]
Hey!
I've been looking online to find a solution to the same problem you had. Could you explain how you managed to fix the issue with ssh? I've got an iPhone 7 and I bought it in Shanghai and I was wondering why I couldn't find anybody else with that problem.
Thanks in advance!

**Comment by VBQL** [comment]
> Hey!
> I've been looking online to find a solution to the same problem you had. Could you explain how you managed to fix the issue with ssh? I've got an iPhone 7 and I bought it in Shanghai and I was wondering why I couldn't find anybody else with that problem.
> Thanks in advance!

Fixed in DM's. This user was not sure about the process of using SSH.
But for anyone else, toggle (Re)Install OpenSSH in unc0ver and re-jailbreak.
Afterwards find your local ip, use a computer and type in the command "ssh root@[ip]"
It will ask to confirm the RSA fingerprint, type yes and continue.
Password is "alpine", you wouldn't see it but trust me it's there
Then do "rm -rf var/preferences/com.apple.networkextension*"
Respring/jailbreak your phone and it should be fixed.

**Comment by compscientist** [comment]
Can you also explain to me how to use SSH? I use a Windows computer so I can't access the phone using terminal.app directly. I tried using PuTTy and it doesn't work. I typed in the IP and 'alpine' and it says wrong password...

**Comment by VBQL** [comment]
Are you using Windows 10? Windows 10 with the newest update comes with SSH installed :)

**Comment by superarts** [comment]
Thanks! To summarize:

1. Go to `unc0ver`, touch gear icon in the top-right cover, and toggle `(RE)Install OpenSSH` to `ON`
2. Re-jailbreak
3. Run `ssh root@IOS_DEVICE_IP` with default password `alpine`
4. Run `rm -rf /var/preferences/com.apple.networkextension*`, or `mv /var/preferences/com.apple.networkextension* /var/root/` if you want to backup them
5. Don't forget to run `passwd` to change default password! Otherwise anyone could log in as root and grab your dirty pictures.
6. Re-sprint; after reboot, re-jailbreak is necessary.

**Comment by armanylo** [comment]
hi guys i am running the same problem, i have a chinise9,2 ios 12.4. I did jailbreak my device but cydia is not connected to the internet. how can i solve it . i dont't understand your methode i tryed to use powershell on my windows but i couldn't make it. maybe because i don't understand very well how to do so. i would be great if you can send me the screenshot on your windows or mac. if you don't mind of course. only if the reel methode is this one. please

**Comment by superarts** [comment]
> hi guys i am running the same problem, i have a chinise9,2 ios 12.4. I did jailbreak my device but cydia is not connected to the internet. how can i solve it . i dont't understand your methode i tryed to use powershell on my windows but i couldn't make it. maybe because i don't understand very well how to do so. i would be great if you can send me the screenshot on your windows or mac. if you don't mind of course. only if the reel methode is this one. please

@armanylo you need to have the basic understanding of how SSH works. Maybe you should take a look at this link to get some general idea:

https://www.howtogeek.com/336775/how-to-enable-and-use-windows-10s-built-in-ssh-commands/

Then you need to make sure you iPhone is on the same network with your SSH client, which is quite simple:

https://www.iclarified.com/496/how-to-find-the-ip-address-of-your-iphone

I put my comments here to summarize the current solution, as well as document some command I used to address this issue. If something else goes wrong for you, there may be some connectivity issue or something else. So if you have further issues, I'd suggest starting a new thread instead of using this closed one.
