### ISSUE TITLE
iPhone 8 stucks in respring loop

### ISSUE THREAD

**Issue by TrickShotMLG02** [pwn20wndstuff/Undecimus#508]
I activated the jailbreak and then I rebooted it. Since then it permanently stucks in a respring loop.
It shows me the apple Logo and the i get a black screen and it restarts so i see the apple logo again.

**Comment by TrickShotMLG02** [comment]
Will the Jailbreak disable itself, when the device runs out of power?

**Comment by Un4givenPG** [comment]
Restore to iOS 12.1b3 right now and wait for a full release, if it boot looped it won't disable itself

**Comment by TrickShotMLG02** [comment]
how can i do that?

**Comment by TrickShotMLG02** [comment]
my pc doesn't reconize my device

**Comment by Un4givenPG** [comment]
Bro you must be really new to jailbreking wait for the full release. It wouldn't be called Public Testing without a reason

**Comment by Un4givenPG** [comment]
Now wait till it restarts

**Comment by TrickShotMLG02** [comment]
ok thanks
and no, I'm not new

**Comment by TrickShotMLG02** [comment]
But i never had a problem like that

**Comment by Un4givenPG** [comment]
You must have experienced a respring loop even once I got even two last week on my testing phone. That's why I'm guessing you are new. There are a plenty solutions for a respring loop (SSH into your device, hard restart, wait till the battery drains) every one that is in jailbreaking for 2 weeks knows that, you posting this as an issue on GitHub prove yourself, as being rather new to it, so please wait for a full stable release, instead of posting fake bug reports.
With regards 
Un4givenPG

**Comment by TrickShotMLG02** [comment]
I fixed it
