### ISSUE TITLE
3.0~b36 no longer works on iOS 11

### ISSUE THREAD

**Issue by opa334** [pwn20wndstuff/Undecimus#589]
Unc0ver 3.0~b36 no longer works on iOS 11.3.1 (iPhone 6 Plus). The phone just reboots on 38/38, even with "Load Tweaks" and "Reload System Daemons" unchecked. Persists even after a rootFS restore.

**Comment by cadbob** [comment]
Have same Phone on IOS 11.4.1 was JB with B26 and went to B36 last night! No Issues what so ever here.

I Icleaned 1st
rebooted Phone
Uninstalled B26
Cydia Impacted in B36
Turned on Airplane Mode
Jail Broke

**Comment by Aerozolic** [comment]
Same issue on b37 on iOS 11.4.1 (iPad Air). After multiple tries and kernel panics it gets to 38/38 then briefly shows a message about jailbreak completed but then it panics and reboots.

**Comment by pwn20wndstuff** [comment]
Oh. I know what’s wrong!! - This happens because the v1ntex exploit doesn’t properly clean up after stealing the kernel credentials. - There’s code in Apple’s sandbox that causes a kernel panic if these stolen credentials get detected. - Older builds used to patch data in Sandbox to break the code. - This build unpatches the data as soon as it gets done with it. - So I will have to change it to not unpatch it.

**Comment by Aerozolic** [comment]
> Oh, I know what’s wrong. - This happens because the v1ntex exploit doesn’t properly clean up after stealing the kernel credentials. - There’s code in Apple’s sandbox that causes a kernel panic if these stolen credentials get detected. - Older builds used to patch data in Sandbox to break the code. - This build unpatches the data as soon as it gets done with it. - So I will have to change it to not unpatch it.

Great! Waiting for the next release then.
PS. Is that considered normal that the exploit fails at step 2 a lot? Before updating to b37 I had to try at least 5 times and 5 reboots before the exploit worked and completed successfully.
