### ISSUE TITLE
iOS 11.4.1 bootlooped with 3.0.0-b38

### ISSUE THREAD

**Issue by andyroid1023** [pwn20wndstuff/Undecimus#649]
My phone was running well for 2-3 days. I have tvOS 12 beta profile, blocked updates with unc0ver. I also make sure that there’s no  OTA update on my phone storage before jailbreaking. One night, I left my phone charging overnight then when I wake up in the morning, I found out that my phone was already in a bootloop.

I didn’t install any pirated and cracked tweaks though. I also make sure that I only install tweaks that are compatible to my firmware version.

Good thing I was able to restore to iOS 12.1.1b3 and futurerestore back to iOS 11.4.1. I’m too scared to jailbreak my phone because it might cause another bootloop. Hope this will be addressed soon.

⚪️ I have a useful screenshot that shows the full log(After pressing the view log button) and will post it.
⚪️ I have exported my Diagnostics file immediately after jailbreak failed or succeeded and will post it.
🔘 I have checked other issues to make sure its not a duplicate issue.
🔘 I am using the latest unc0ver beta.
🔘 I have checked to see if my device and iOS version are supported.
🔘 I can accurately describe the issue in the description and maintain a descriptive but short title.
🔘 I will not have more than one issue actively open at once.
🔘 I will not be entitled, spam, or use ??? or !!!.

**Comment by DavidNC1978** [comment]
This actually is the SAME exact thing that happened to me a few days ago.  I had Unc0ver installed and running on my iPhone-6 on 11.4.1 and every night my phone rebooted itself randomly overnight when it was plugged into a charger (but I have to charge my phone somehow).  A few days ago it did the random reboot and when I went to re-JB it sent me into a bootloop, so bad in fact that my iPhone wouldn’t even restore to stock iOS.  I had to file an insurance claim as a malfunction of the phone and get a replacement phone.  And since my phone won’t restore I have no way to wipe the phone out clean before I send it to my insurance company for the replacement.  It’s very strange how this happened and I have no way to sending a log since it doesn’t respond to anything I do.  In all my 11 years of JB this is the first time it has bricked a phone.  Luckily I was upgraded to an iPhone-6S on 11.3 and so far running smoothly but still getting random reboots...
