### ISSUE TITLE
Slowly chargeing on unsupport cable b38(iOS 12.0 SE и iOS 12.1.2 6s)

### ISSUE THREAD

**Issue by vladellec** [pwn20wndstuff/Undecimus#664]
**Describe the bug**
Phone slowly chargeing on not-original cable in b38(noticed on iOS 12.0 SE and iOS 12.1.2 6s)
If jailbroken, speed charge normally.

**Device**
 - iOS Version: 12.0/12.1.2
 - iOS Device: SE/6s
 - unc0ver Version: b38

**Place an "x" between the brackets if true:**
 - [X ] this is a bug others will be able to reproduce
 - [X ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X ] this issue is present after a rootfs restore
 - [X ] this issue is present on the latest version of unc0ver
**Logs**
From SE
[diagnostics.zip](https://github.com/pwn20wndstuff/Undecimus/files/2923363/diagnostics.zip)

**Comment by Un4givenPG** [comment]
Bro, report issues the right way please, not like that, it won’t help Pwn at all.
Give your logs etc.

**Comment by vladellec** [comment]
update, thanks!

**Comment by Mas9311** [comment]
diagnositics.plist @ line 6245 confirms that you are jailbroken. 

I'm having a hard time understanding what the issue is about. If I'm understanding your issue correctly:
 - you want to request a feature. if jailbroken: speed charge the phone.

Does this statement correctly describe your issue?
 - If so, this is not related to unc0ver. Instead, make a [Request] post to the [r/jailbreak](https://www.reddit.com/r/jailbreak/) community.

Also, you should update to b39 [:

**Comment by vladellec** [comment]
ok
