### ISSUE TITLE
Why I don’t jailbreak?

### ISSUE THREAD

**Issue by LoSel2** [pwn20wndstuff/Undecimus#693]
I can't jailbreak the ios12 iphone6. I've always tried using unc0ver in beta38 but still can't.
Plese help me...

![](https://www.img.in.th/images/c61548da2eac4e8f142c4fb0116ee07e.png)

**Comment by kubmin** [comment]
I guess you should delete your OTA file, as the error suggests.

https://www.theiphonewiki.com/wiki/OTA_Updates

**Comment by CoolPersonMaam** [comment]
Looked at the logs and it looks like your RootfS is 12.1.4 which is not what it’s suppose to be. Since you’re not jailbroken yet. You can safely do a reset alll content and settings and this will not boot loop your devix

Apparently, you let the update download but now it’s pending and no longer in storage. Backup your device before doing this

**Comment by LoSel2** [comment]
@kubmin I no have OTA on storage.
@CoolPersonMaam What should I do?
Can you explain more thoroughly?

**Comment by CoolPersonMaam** [comment]
To keep it simple: 
Your current RootFS is 12.1.4
You cannot fix this by doing a restore RootFS 
Therefore you will have to back up your device and do a restore content and settings DO NOT RESTORE VIA ITUNES it will upgrade to 12.1.4

**Comment by LoSel2** [comment]
@CoolPerMaam Is there any way to fix RootFS
Help me plese. I am beginner

**Comment by coenkcore** [comment]
Update to uc0ver 3.0.0~b43 

https://twitter.com/jakeashacks/status/1103747007745835011?s=21

**Comment by LoSel2** [comment]
Thx @coenkcore I will try doing it.

**Comment by LoSel2** [comment]
Ok that’s work thank you very much.
