### ISSUE TITLE
exploit failed

### ISSUE THREAD

**Issue by Spasix** [pwn20wndstuff/Undecimus#709]
"exploit failed!" error on iPad Air 12.1.2 Beta. The version of Beta is 16D5024a. It’s an iPad Air WiFi edition. 

Every time I jailbreak it shows “kernal_task error”.
Sorry if I can’t provide a screenshot right now. I will just describe the issue. 

I click jailbreak and it runs as it is supposed to but when it reached step 2 it stops and a error pops up saying “kernal_task” error. I rebooted my iPad and removed the passcode and did everything others offered. As I read the log window it says “Exploit failed!). 

I have posted an screenshot on my twitter [@SmitPatelTYZ]. You should find it there.

**Comment by Mas9311** [comment]
Are you sure it is running iOS 12.1.2 Beta? Please humor me and go into Settings > General > About > Version. Does it say 12.1.1 (16C5050a)? If so, that is 12.1._**1**_ Beta 3

This issue is not descriptive enough to help the devs out. It needs more to describe what is happening in order for it the exploit to fail. Please include your logs, and which iPad it is. Examples of the different iPads are below:

 - **iPad4,1** = iPad Air (Wi-Fi)
 - **iPad4,2** = iPad Air (Wi-Fi + Cellular)
 - **iPad4,3** = iPad Air (Wi-Fi + Cellular CN)
 - **iPad5,3** = iPad Air 2 (Wi-Fi)
 - **iPad5,4** = iPad Air 2 (Wi-Fi + Cellular)

**Comment by airsquared** [comment]
You didn't fill out the bug report template and didn't follow the issue guidelines. Please close this issue and create a new one with the template filled out.

**Comment by CoolPersonMaam** [comment]
@airsquared lmao you’re copy and pasting lol

What did the screenshot look like did it restart did it say fail to escape sandbox

Try restarting 

Also please create a new issue we don’t know what you’re talking about

**Comment by coenkcore** [comment]
@coolpersonmaam
Read the guidlines before creating new issue dude.
