### ISSUE TITLE
Reboot Loop

### ISSUE THREAD

**Issue by theLaxerz** [pwn20wndstuff/Undecimus#743]
Goes through JB if AirPlane mode is off, however reboots after respring.  Goes to 38/38 if on but Jailbroken popular never shows. This is in B40/41

**Comment by Mas9311** [comment]
Update to ~b43 (current beta release as of writing this), because I had this problem with pre b41 releases.
If it persists, then one-by-one disable the following options and attempt Jailbreak again:
 - Increase Memory Limit (Beta).
 - Reload System Daemons.
 - Reinstall Cydia.
 - Refresh Icon Cache.

You should be able to jailbreak somewhere in there ¯\\\_(ツ)\_/¯

**Comment by aaronlax420** [comment]
Thanks I managed to get it going but had to restore rootfs
