### ISSUE TITLE
Cydia takes a long time to open

### ISSUE THREAD

**Issue by mac-user669** [pwn20wndstuff/Undecimus#748]
**Describe the bug**
When I open Cydia, even in safemode, it will take about a minute to even show the home page. It also takes a while to Reload Data
**To Reproduce**
1. Open Cydia
2. See Error

**Screenshots**
N/A

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPhone 5s
 - unc0ver Version: 3.0.0b41

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [x] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

**Logs**
N/A imo

**Comment by Mas9311** [comment]
I do agree with one detail of this issue: 
 - opening Cydia takes a while to show the Home page 

(confirmed with safemode and/or airplane mode enabled).

- - -

>  [x] this issue is present on the latest version of unc0ver

False. ~b43 is the current beta version (as of writing this). Problem persists, but just a reminder to stay updated.

- - -

Cydia has always taken a while to reload. This happens every time you open Cydia, with the exception of re-opening in a 15 minutes window. _Pretty_ sure it's equivalent to Linux's <code>sudo apt-get update</code> on **all** of your repos. 
To speed it up, you _can_ remove any unused repos to speed it up. I don't recommended it though, because:
 1. It _might_ break your refresh if you have a package installed through that repo. But don't quote me [:
 1. You won't know what that dev has updated to iOS 12! This is my go-to place to install a packages. If it's on the changes tab, then there's a 99% chance it is compatible with iOS 12. (Anything that ends with a capital X is not for 5S).

**Comment by me246813579** [comment]
I have b43 on my iPad Air, and the same thing happens
