### ISSUE TITLE
ErrNo: 2/ Test: “BuildVersions match” ==NULL

### ISSUE THREAD

**Issue by drxrxy** [pwn20wndstuff/Undecimus#789]
When I try to jailbreak using b46 I keep getting [ErrNo: 2/ Test: “BuildVersions match” ==NULL
File name: JailbreakViewController.m 
Line: 1156
Function: Jailbreak
Description: RootFS already mounted, delete OTA file from settings.]

I’ve checked and checked and the OTA file is not present. I’ve uninstalled Unc0ver and rebooted device. Reinstalled and tried to use Cydia Impactor and/or use untethered apps but nothing works. 

Any solutions?
iPhone - XS Max 11,6
Ver- 12.1.1~b3
Unc0ver- b44-b46

**Comment by kendallkoontz** [comment]
Exact same setup as me. I’ve tried attempting changing settings of Unc0ver to no avail. It seems to not be user error.

**Comment by mdau2508** [comment]
Having the same issue

**Comment by mastermindman13** [comment]
Had the same issue. My fix was to restart the phone after the error then:
1. Open unc0ver
2. Change the “Disable auto updates” to be off
3. Jailbreak it but you will have the same error message as before
4. Restart the phone again
5. Go to software update in settings and let it download the update 
6. Delete the ota update and wait for 2 minutes for the ota to be completely removed 
7. Start unc0ver again and hopefully your problem is solved

**Comment by andrzej-grala** [comment]
> Had the same issue. My fix was to restart the phone after the error then:
> 
> 1. Open unc0ver
> 2. Change the “Disable auto updates” to be off
> 3. Jailbreak it but you will have the same error message as before
> 4. Restart the phone again
> 5. Go to software update in settings and let it download the update
> 6. Delete the ota update and wait for 2 minutes for the ota to be completely removed
> 7. Start unc0ver again and hopefully your problem is solved

That was very helpful. Thank you!

**Comment by cjsworld** [comment]
Delete OTA files, reboot, and reinstall unc0ver. That worked for me!
