### ISSUE TITLE
Certain tweaks causing respring loops due to a (probably) substrate bug

### ISSUE THREAD

**Issue by jakeajames** [pwn20wndstuff/Undecimus#799]
**Describe the bug**
We all know what, respring loops.

**To Reproduce**
1. Jailbreak with "Reload System Daemons" while having certain tweaks enabled

**Device (please complete the following information):**
 - iOS Version: 12.1.2
 - iOS Device: iPad Air 2
 - unc0ver Version: b46

**Place an "x" between the brackets if true:**
 - [x] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [x] this issue is present after a rootfs restore
 - [x] this issue is present on the latest version of unc0ver

Certain tweaks seem to trigger respring loops. First rocketbootstrap, then Snowboard & many others. Those two examples were updated, but they did not fix bugs in their code, rocketbootstrap did some hack while Snowboard stopped hooking certain processes. After the latest versions of both, I still had respring loops, based on how Snowboard was updated, I decided to disable some daemon tweaks (AFC2 etc) and the issue stopped happening. This makes me think this is not an issue with specific tweaks, but rather on substrate's end, which makes hooking certain daemons cause issues.

**Comment by seeskyline** [comment]
@jakeajames 

I have the same problem.  Once the tweak's plist filter includes  com.apple.corelocation then the respring loop appears, even if the there is no code in the tweak. It seems that some daemons cannot be hooked when they are being reloaded.  I agree with  @jakeajames that it is a bug of substrate,  not the tweak itself.

**Comment by seeskyline** [comment]
@jakeajames

I have the same problem. Once the tweak's plist filter includes com.apple.corelocation then the respring loop appears, even if the there is no code in the tweak. It seems that some daemons cannot be hooked when they are being reloaded. 

I agree with @jakeajames that it is a bug of substrate, not the tweak itself. However, if unc0ver can find a way to get around it, then every one will be happier, because this problem really makes some jailbroken users frustrated.
