### ISSUE TITLE
LeMeBlock update are being over written by unc0ver.

### ISSUE THREAD

**Issue by mwoolweaver** [pwn20wndstuff/Undecimus#820]
When I update the LetMeBlock package in Cydia everything is ok until I have to rejailbreak and then unc0ver installs version 0.1 again. Is there any way the package could be updated within unc0ver or a check could be added so that this cycle can be broken?

**Comment by KH12** [comment]
replace new file with old file in path /var/lib/undecimus/apt

delete old file deb LetMeBlock and paste new file deb and again rejailbreak . then check cydia for updates its ok or no

**Comment by mwoolweaver** [comment]
Any way you could provide a link to download com.bingner.plutil ?

**Comment by mwoolweaver** [comment]
https://imgur.com/gallery/crCvaBM

Now I get this error.

**Comment by pwn20wndstuff** [comment]
This issue is happening because the package fails unc0ver’s package verification. This happens because the developer bundles a file in his package that he removes on installation. unc0ver goes to great lengths of verifying the integrity of its resources/default packages, so LetMeBlock fails the verification due to the missing file. This is not an unc0ver bug and this verification issue applies for dpkg itself too. I have talked to the developer and I think he will soon fix this and push an update to his package.

**Comment by mwoolweaver** [comment]
LetMeBlock 0.5 update fixes this issue.

**Comment by anddilolz** [comment]
I replaced "com.ps.letmeblock_0.0.1_iphoneos-arm.deb" with "com.ps.letmeblock_0.0.6.6-2_iphoneos-arm.deb" in /var/lib/undecimus/apt and it's giving me the [debsToRepair error](https://imgur.com/gallery/crCvaBM). LetMeBlock 0.0.5 is not available anymore so I couldn't try with that version. Perhaps the new version of LetMeBlock re-introduced the missing file problem, and the verification fails again?
