### ISSUE TITLE
Random reboots

### ISSUE THREAD

**Issue by lberrezoug** [pwn20wndstuff/Undecimus#894]
**Describe the bug**
Hello team, 
the springboard freezes and after a while the phone reboot, it happens to me from time to time.

**Device :**
 - iOS Version: 12.1.1
 - iOS Device: iPhone7
 - unc0ver Version: 3.0.0~b48

 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [X] this issue is present on the latest version of unc0ver

[panic-full-2019-03-27-093345.714.ips.synced.txt](https://github.com/pwn20wndstuff/Undecimus/files/3013473/panic-full-2019-03-27-093345.714.ips.synced.txt)

[panic-full-2019-03-27-120106.447.ips.synced.txt](https://github.com/pwn20wndstuff/Undecimus/files/3013471/panic-full-2019-03-27-120106.447.ips.synced.txt)

**Comment by ouadahi** [comment]
Same problem

Device :
iOS Version: 12.1.2
iOS Device: iPhone SE
unc0ver Version: 3.0.0~b45

this is a bug others will be able to reproduce
this issue is present with all tweaks uninstalled(except for default packages) or disabled
this issue is present after a rootfs restore
 x this issue is present on the latest version of unc0ver

[panic-full-2019-03-19-220657.088.txt](https://github.com/pwn20wndstuff/Undecimus/files/3013879/panic-full-2019-03-19-220657.088.txt)

**Comment by hazysimmers13** [comment]
Yep I’m having the same problem I’ll wake up it’s in safe mode. Also when I try to rearrange my apps on the springboard,it either respirings or goes into safe mode.

**Comment by tsxmichael** [comment]
First random reboot on my a12

iOS Version: 12.1.2

iOS Device: iPhone XS Max 

unc0ver Version: 3.0.0~b48

https://mega.nz/#!7QYVSKjR!fEga-QajGI5iprgAp00BDqQJLykKTgsGn7l8t4XmFqs

**Comment by spikesF** [comment]
freeze(while using Discord) then reboot iPhone 6 plus iOS 12.1.2 here the panic file latest unc0ver beta(b48)

> ”is’t reproducable? maybe just use discord app for while”

[panic-full-2019-03-28-091414.txt](https://github.com/pwn20wndstuff/Undecimus/files/3016813/panic-full-2019-03-28-091414.txt)

**Comment by IZNEK** [comment]
Describe the bug
Hello team,
the phone reboot without any freeze, it happens randomly.

Device :
iOS Version: 12.1.1
iOS Device: iPhone SE
unc0ver Version: 3.0.0~b48

- [ ]   this is a bug others will be able to reproduce
- [ ]   this issue is present with all tweaks uninstalled(except for default packages) or disabled
- [x]   this issue is present after a rootfs restore
- [x]   this issue is present on the latest version of unc0ver

[panic-full-2019-03-28-203043.txt](https://github.com/pwn20wndstuff/Undecimus/files/3023139/panic-full-2019-03-28-203043.txt)

[panic-full-2019-03-29-143021.txt](https://github.com/pwn20wndstuff/Undecimus/files/3023140/panic-full-2019-03-29-143021.txt)

**Comment by Louloucest** [comment]
Same problem iPhone reboot in safe mode randomly

**Comment by tsxmichael** [comment]
Its gonna be fix by the next update today! I believe

**Comment by 2600box** [comment]
Reboot on my a12 - was using twitter at the time

iOS Version: 12.1

iOS Device: iPhone XS

unc0ver Version: 3.0.0~b48


[panic-full-2019-04-01-104613.txt](https://github.com/pwn20wndstuff/Undecimus/files/3027616/panic-full-2019-04-01-104613.txt)

**Comment by lberrezoug** [comment]
Hello team,
unfortunately I always have a random restart with the latest version, I got it two times and in both cases the restart occurred when I tried to take a photo.

I have attached the last panic-full log file so that you can do a troubleshooting.

PS: I thank you very much for your work and devotion to the community

Device :
iOS Version: 12.1.1
iOS Device: iPhone7

unc0ver Version: 3.0.0~b49

X this issue is present on the latest version of unc0ver
[panic-full-2019-04-08-101220.698.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/3053615/panic-full-2019-04-08-101220.698.ips.txt)

**Comment by lberrezoug** [comment]
Hi,
The same scenario, when I want to send a picture on vibrate my phone crashes and restarts.
Unfortunately it's random, I don't know how to reproduce this phenomenon.

thank you 

[panic-full-2019-04-10-222340.386.ips.txt](https://github.com/pwn20wndstuff/Undecimus/files/3068063/panic-full-2019-04-10-222340.386.ips.txt)
