### ISSUE TITLE
respring loop after jailbreak IphoneX 12.1.1 on b48

### ISSUE THREAD

**Issue by LLRI** [pwn20wndstuff/Undecimus#905]
**Describe the bug**
After the jailbreak with b48, i see the respring wheel turning forever, i have to reset the phone and go back to b46 (b46 work perfectly)

**To Reproduce**
jailbreak my iphonex with b48

**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: iphone x
 - unc0ver Version: b48

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by LLRI** [comment]
But this issue seem to be fixed if i turn off "Reload System Daemons"

**Comment by issacgithub** [comment]
The tweaks that make respring loop on iPhone 7+ are:
StatusTint (libCSpreferences -libSparkAppList)
Gif2Any(libCSPreference)
Yourespring(libdevImagePick)
libmitsuha
AppCake v6.1.1 from source:HackYourIphone(you should install from Main source(AppCake Source))

I've tested all of these on my phone

If some of these tweaks are installed from the original source, Or tweaks to be upgraded this issue is likely to be fixed
Thanks

**Comment by Mrlobbies** [comment]
Was having a similar issue jailbroke with daemon and tweaks turned off removed the last installed tweak I remembered and it started working again.

**Comment by moks84** [comment]
OK now the phone keep restarting then resping wheel again and again.
how should this be fixed ?
