### ISSUE TITLE
Keeps restoring rootfs

### ISSUE THREAD

**Issue by h3716041** [pwn20wndstuff/Undecimus#92]
I have an iPhone X iOS 11.2.1 and every time I try to jailbreak, it keeps restoring rootfs. After it is done doing that the phone restarts and nothing happens. The toggle to restore rootfs is always off but it keeps restoring it anyway.

**Comment by Samgisaninja** [comment]
This is an issue with coolstar/electra1131

The rootfs backup that Electra makes on first jailbreak... *contains electra* and therefore cant be removed automatically by unc0ver

You should install and use electra once, then run the Delectra script kivoair/delectra and then switch to unc0ver.

**Comment by KBrownies** [comment]
Hey Samgisaninja,

 Okay so here is my situation I was first jailbroken with Electra on my iPhone 7 that's on iOS 11.2.6 . So what I did was is I uninstalled all of my tweaks and any left over directories from the tweaks. So the only packages left installed were the ones for Cydia. So it was just like I was freshly jailbroken with Electra. So then what I did was delete the Electra app and rebooted my iPhone. Then I uses the Restore RootFS option in UnC0ver to restore RootFS. But after multiple tries and multiple reboots Cydia app was still on my device. Then finally I noticed it was gone. So I figured okay maybe this finally worked and I can jailbreak. So I rebooted my phone, and tried to jailbreak but it kept restoring RootFS even tho the option was toggled off. Then I figured well since Cydia was gone from restoring RootFS. I backed up my device and then I restored my device via the settings app. And then loaded my backup back onto my device. Then I tried to jailbreak with unc0ver again and it still kept restoring RootFS and rebooting once done. Then I saw this issue and so I jailbroke my iPhone again with Electra and then ssh'ed the Delectra file into /electra and used terminal on my laptop to ssh into my phone and run the shell script. And then it completed successfully. So now Cydia was gone. So I deleted the Electra app. Rebooted my iPhone one more time for safe measure, and tried to use unc0ver again to jailbreak and I still keep getting the same exact issue where it just continues to restore RootFS even tho the toggle is off. Do you have any idea on what else I could do to try to fix this issue? I'm using the latest version on Unc0ver by the way. 

Thanks!

**Comment by Samgisaninja** [comment]
Re-opened because we’re attempting to fix this on our end even though it’s not our fault

**Comment by KBrownies** [comment]
Hey Samgisaninja,

I found a solution on reddit in order to jailbreak with Unc0ver. It's this tutorial right here. Credit goes to Reddit user /u/wb0815

Tutorial that worked for me.

Reboot > install Electra, toggle OFF tweak and hit Jailbreak > run delectra script again > device will reboot when completed > then go to setting > general > reset > hit erase all content and setting > device now full unjailbreak (make sure you already do backup iTunes). After that, do not restore backup device and do not login iCloud on the first place > just jailbreak with unc0ver and it should work now. 

Now here's the other issue... After I jailbroken my iPhone with Unc0ver 1.1.1 I rebooted my iPhone and then restored my backup data to my iPhone and after it was done restoring my backup data to my iPhone and now when I try to jailbreak with my iPhone using unc0ver, it gets stuck at 37 and then gives me this error.

~~~
Error

Errno: 2

Test: daffodils("/var/tmp/jailbreakd.pid") == 0
Filename: ViewController.m
Line: 2186
Function: exploit
Description: Failed to spawn jailbreakd 
~~~

And after the pop up for this error it crashes the unc0ver application and I continue to get this error every time after I reboot and try again. Do you think that since now my phone is jailbroken with Unc0ver, should I do a RestoreFS and try jailbreaking my iPhone again? Or do I just need to keep trying the jailbreak until it goes thru? I'm using the MP (MultiPath) exploit. 

Please let me know if you need anymore information.

**Comment by Cryptiiiic** [comment]
@KBrownies can you post your diagnostics exported from unc0ver utilities section.
