### ISSUE TITLE
Reinstall after every reboot

### ISSUE THREAD

**Issue by BlueFirePup** [pwn20wndstuff/Undecimus#933]
**Describe the bug**
have to reinstall after every reboot

**To Reproduce**
reboot device

**Screenshots**
None Available

**Device (please complete the following information):**
 - iOS Version: 12.1.1
 - iOS Device: A1901 iPhone X
 - unc0ver Version:  Undecimus-v3.0.0-b49
**Place an "x" between the brackets if true:**
 - [ X] this is a bug others will be able to reproduce
 - [X ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [X ] this issue is present after a rootfs restore
 - [X ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by heat200** [comment]
I've had this happen once on b49. hasn't happened since, admittedly this had occurred with the M1 kernel exploit. When I reinstalled Unc0ver via Cydia Impactor I failed to jailbreak multiple times with the same M1 exploit. Have switched to the VS exploit and that has it working ALTHOUGH I am experiencing full kernel panics. I am currently 3 kernel panics in since starting to use b49
