### ISSUE TITLE
Re-install Open SSH

### ISSUE THREAD

**Issue by deucetresthugz** [pwn20wndstuff/Undecimus#970]
**Describe the bug**
A clear and concise description of what the bug is and what you expected to happen.

**To Reproduce**

**Screenshots**

**Device (please complete the following information):**
 - iOS Version: 
 - iOS Device: 
 - unc0ver Version: 

**Place an "x" between the brackets if true:**
 - [ ] this is a bug others will be able to reproduce
 - [ ] this issue is present with all tweaks uninstalled(except for default packages) or disabled
 - [ ] this issue is present after a rootfs restore
 - [ ] this issue is present on the latest version of unc0ver

**Logs**
If applicable, add logs or error messages here.

**Comment by sss3914** [comment]
How dawnlod

Sultan almuteiri ‬

‫في 20‏/04‏/2019 الساعة 7:38 م، كتب/كتبت ‏deucetresthugz ‏<notifications@github.com<mailto:notifications@github.com>>:‬


Describe the bug
A clear and concise description of what the bug is and what you expected to happen.

To Reproduce
Steps to reproduce the behavior:

  1.  Go to '...'
  2.  Click on '....'
  3.  Scroll down to '....'
  4.  See error

Screenshots
If applicable, add screenshots to help explain your problem.

Device (please complete the following information):

  *   iOS Version:
  *   iOS Device:
  *   unc0ver Version:

Place an "x" between the brackets if true:

  *    this is a bug others will be able to reproduce
  *    this issue is present with all tweaks uninstalled(except for default packages) or disabled
  *    this issue is present after a rootfs restore
  *    this issue is present on the latest version of unc0ver

Logs
If applicable, add logs or error messages here.
